# Generated by Django 3.2.9 on 2022-08-22 13:04

import core.models
import core.storage
import datetime
from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import embed_video.fields
import location_field.models.plain
import multiselectfield.db.fields
import phonenumber_field.modelfields
import taggit_autosuggest.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities_light', '0010_auto_20200508_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hide_ads_tab', 'Hide ads tab'), ('hide_campaigns_tab', 'Hide campaigns tab'), ('crm_can_view_comn_dashboard', 'CRM | Can view communication dashboard'), ('crm_can_view_oper_dashboard', 'CRM | Can view dashboard'), ('crm_can_view_pin_boards', 'CRM |  Can view pin boards'), ('crm_can_view_comn_agenda', 'CRM |  Can view communication agenda'), ('crm_can_view_contact_list', 'CRM |  Can view contact list'), ('crm_can_view_simplified_contact_list', 'CRM |  Can view simplified contact list'), ('crm_can_view_follow_up_list', 'CRM |  Can view follow up list'), ('crm_can_view_sms_email', 'CRM | Can view sms & emails'), ('crm_can_view_offer_list', 'CRM | Can view offer list'), ('crm_can_view_expired_ponctual_events', 'CRM | Can view expired ponctual events'), ('crm_can_view_comm_dashboard', 'CRM | Can view commercial dashboard'), ('crm_can_view_comm_agenda', 'CRM | Can view commercial agenda'), ('crm_can_view_prospect_list', 'CRM | Can view prospect list'), ('crm_can_manage_prospect_list', 'CRM | Can manage prospect list'), ('crm_can_manage_pistes', 'CRM | Can manage pistes'), ('crm_can_view_command_list', 'CRM | Can view command list'), ('crm_can_view_untreated_command_list', 'CRM | Can view untreated command list'), ('crm_can_view_bordereau_list', 'CRM | Can view bordereau list'), ('crm_can_view_viement_list', 'CRM | Can view viements'), ('crm_can_view_invoice_list', 'CRM | Can view invoice list'), ('crm_can_view_tech_dashboard', 'CRM | Can view technician dashboard'), ('crm_can_view_tech_agenda', 'CRM | Can view technician agenda'), ('crm_can_view_problem_list', 'CRM | Can view problem list'), ('crm_can_view_delg_agenda', 'CRM | Can view delegue agenda'), ('crm_can_create_demand', 'CRM | Can create new demand (tech, commercial ..)'), ('crm_can_create_command', 'CRM | Can create new command (Offre Prépayée ..)'), ('crm_can_create_action_punctual_follow_up', 'CRM | Can create action type: suivi ponctuel'), ('manage_tasks', 'CRM | Manage tasks'), ('crm_timeline_can_add_detail', 'CRM | timeline Can add detail'), ('crm_timeline_can_add_technical_detail', 'CRM | timeline Can add technical detail'), ('crm_timeline_can_close_piste', 'CRM | timeline Can close timeline'), ('crm_timeline_can_set_demand_as_done', 'CRM | timeline can set demand as done'), ('crm_timeline_crm_can_add_next_meeting', 'CRM | timeline Can add next meeting'), ('crm_timeline_can_create_account', 'CRM | timeline Can create account for new contact'), ('crm_timeline_can_create_untreated_order', 'CRM | timeline Can create an untreated order for new contact'), ('care_can_view_dashboard', 'CARE | Can view dashboard'), ('care_can_view_profile', 'CARE | Can view profile'), ('can_view_etabib_store', 'CARE | Can view etabib store'), ('can_view_etabib_expos', 'CARE | Can view etabib expos'), ('can_view_etabib_econgre', 'CARE | Can view etabib econgre'), ('can_get_expo_badge', 'CARE | Can get expo badge'), ('can_veiw_e_prescription', 'CARE | Can view E-prescription'), ('can_veiw_teleconsultation', 'CARE | Can view teleconsultation'), ('can_veiw_agenda', 'CARE | Can view agenda'), ('can_veiw_etabib_file_sharing', 'CARE | Can view etabib file sharing'), ('can_view_drugs_list', 'CARE | Can view drugs list'), ('can_view_test_dicom', 'Demo | Can Test Dicom')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_debut_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Heure de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_fin_time', models.TimeField(default=datetime.time(23, 59), verbose_name='Heure de fin')),
                ('type', models.CharField(choices=[('1', 'Suivi Actif'), ('2', 'Suivi Ponctuel'), ('3', 'Intervention Technique'), ('4', 'Demande de Formation'), ('5', 'Demande commerciale')], default='1', max_length=2, verbose_name='Type')),
                ('attribuee_a_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('external_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien externe')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AnnonceClickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_click', models.DateTimeField(verbose_name='date de clic')),
                ('reseau', models.CharField(blank=True, choices=[(1, 'En Ligne'), (2, 'eTabib Workspace'), (3, 'Applications de eTabib'), (4, 'Applications mobile'), (5, 'Affichage CONGRES')], max_length=2, null=True)),
                ('cout', models.IntegerField(default=0, verbose_name='coût')),
            ],
            options={
                'verbose_name': 'Annonce Clic log',
                'verbose_name_plural': 'Annonces Clic log',
            },
        ),
        migrations.CreateModel(
            name='AnnonceFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=core.models.get_file_path)),
                ('type', models.CharField(blank=True, choices=[('1', '728x90'), ('2', '450x416'), ('3', '200x360'), ('4', '500x360'), ('5', '728x360'), ('6', '1600x840')], max_length=2, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceImpressionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_impression', models.DateTimeField(verbose_name='date impression')),
                ('reseau', models.CharField(blank=True, choices=[(1, 'En Ligne'), (2, 'eTabib Workspace'), (3, 'Applications de eTabib'), (4, 'Applications mobile'), (5, 'Affichage CONGRES')], max_length=2, null=True)),
                ('cout', models.IntegerField(default=0, verbose_name='coût')),
            ],
            options={
                'verbose_name': 'Annonce Impression log',
                'verbose_name_plural': 'Annonces Impressions log',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='produits/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatar/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('bic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BddScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='the accepted format is X.Y.Z.W', max_length=100, validators=[django.core.validators.RegexValidator('^(\\d+\\.)+(\\d+\\.)+(\\d+\\.)+(\\*|\\d+)$', code='invalid_version_number', message='Version number must be in the format X.Y.Z.W')])),
                ('last_version', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('zipfile', models.FileField(upload_to='bddscripts', validators=[core.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=False)),
                ('verifie', models.BooleanField(default=True, verbose_name='Vérifiée')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CampagneStatistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarteID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_avant', models.FileField(blank=True, default='default_face_card_id.png', null=True, upload_to=core.models.get_carteid_path)),
                ('image_arriere', models.FileField(blank=True, default='default_pile_card_id.png', null=True, upload_to=core.models.get_carteid_path)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', "Carte d'Identité"), ('2', 'Carte Chifa')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CarteProfessionnelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default_card.png', upload_to='cartes/%Y/%m/%d/')),
                ('checked', models.BooleanField(default=False, verbose_name='vérifié')),
                ('rejected', models.BooleanField(default=False, editable=False, verbose_name='rejetée')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='raison du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('npages', models.IntegerField(verbose_name='N°page')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('image', models.ImageField(help_text="L'image doit avoir une largeur de 840px et une hauteur de 1120px, avec une taille < 2Mb", upload_to='catalogue', validators=[core.models.validate_image])),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='titre')),
                ('titre_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='titre')),
                ('titre_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='titre')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificat/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('verifie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClotureAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorisations', models.CharField(choices=[('1', "C dans l'Année (Froid)"), ('2', 'A dans le Semestre (Chaud)'), ('3', 'B dans le Trimestre (Tiède)')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('texte', models.TextField()),
            ],
            options={
                'verbose_name': 'Commentaire sur les modules',
                'verbose_name_plural': 'Commentaires sur les modules',
            },
        ),
        migrations.CreateModel(
            name='ComptePreCree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Compte pré-créé',
                'verbose_name_plural': 'Comptes pré-créés',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place id')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=5, null=True, verbose_name='Sexe')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('gps', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('geo_coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('fixe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Fixe')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Mobile (prive)')),
                ('mobile_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Mobile 1 (public)')),
                ('mobile_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone Mobile 2 (public)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction')),
                ('organisme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisme')),
                ('departement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Département')),
                ('commune', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commune')),
                ('codepostal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('type_structure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type Structure')),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('date_debut_exercice', models.DateField(blank=True, null=True, verbose_name="Date de début d'exercice")),
                ('type_exercice', models.CharField(blank=True, choices=[('1', 'projet installation PRIVE'), ('2', 'PRIVE installation < 6mois'), ('3', 'PRIVE installation 6mois <1 ans'), ('4', 'PRIVE installation 1- 5 ans'), ('5', 'PRIVE instatllation > 5 ans'), ('8', 'PRIVE'), ('6', 'Public'), ('7', 'Non connu')], default='7', max_length=2, null=True, verbose_name='Type Exercice')),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name="Années d'expériences")),
                ('pageweb', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Page Web/Site Web')),
                ('facebook', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('maps_url', models.URLField(blank=True, null=True, verbose_name='Lien Maps')),
                ('source', models.CharField(blank=True, choices=[('1', 'Le client se déplace chez nous'), ('2', 'Le client nous envoi un SMS'), ('3', 'Le client nous appelle par tel'), ('4', 'Le client nous envoi un mail'), ('5', 'Le client nous envoi un message réseau sociaux'), ('6', 'Le client nous laisse un message sur le site'), ('7', 'cest un prospect issue de notre recherche'), ('8', 'Le client inscrit sur notre site'), ('9', 'Société savante'), ('10', 'Facebook'), ('11', 'LinkedIn'), ('12', 'Bouche à oreille'), ('13', 'Par laboratoire'), ('14', 'SIMEM21'), ('15', 'LISTE FOSC'), ('16', 'Maps')], max_length=2, null=True, verbose_name='Source')),
                ('motif', models.CharField(blank=True, choices=[('1', 'Demande achat'), ('2', 'Demande devis'), ('3', 'Demande essai'), ('4', 'Autre')], max_length=2, null=True, verbose_name='Motif du contact')),
                ('carte', models.FileField(blank=True, null=True, upload_to='cartes/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mdp_genere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de pass généré')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('compte_test', models.BooleanField(default=False, verbose_name='Compte de test')),
            ],
        ),
        migrations.CreateModel(
            name='ContactezNous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('object', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contactez Nous',
                'verbose_name_plural': 'Contactez Nous',
            },
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('en_rapport_avec', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeInterventionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='demande_intervention/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'Prospection première tentative'), ('02', 'Prospection deuxième tentative'), ('03', 'Prospection troisième tentative'), ('04', 'Prospection quatrième tentative'), ('05', 'Clôture de la piste de prospection'), ('A', 'Prise de contact'), ('B', 'Présentation'), ('C', 'Conclusion imminente'), ('D', 'Déplacement Visite'), ('E', 'Phase Essai'), ('F', 'Récolte Feed Back'), ('P', 'Proposition commerciale'), ('N', 'Négociation'), ('R', 'Recouvrement'), ('MC', 'Marché conclu'), ('L', 'Fidélisation'), ('I', 'Intervention technique')], max_length=2, null=True)),
                ('decision', models.CharField(blank=True, choices=[('0', 'Relance dans'), ('1', 'Suivi Ponctuel')], max_length=2, null=True, verbose_name='Décision à faire')),
                ('decision_nb_jour', models.IntegerField(blank=True, null=True, verbose_name='Nombre de jours')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailActionAudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='action/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailActionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='action/%Y/%m/%d/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date de ajout')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeSoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirme', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipe de Soins',
                'verbose_name_plural': 'Équipe de Soins',
            },
        ),
        migrations.CreateModel(
            name='Etabib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='the accepted format is X.Y.Z', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(\\d+\\.)+(\\d+\\.)+(\\*|\\d+)$', code='invalid_version_number', message='Version number must be in the format X.Y.Z')])),
                ('zipfile', models.FileField(upload_to='etabib', validators=[core.models.validate_file_extension])),
                ('consommation', models.IntegerField(default=0)),
                ('lastversion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier', models.BooleanField(default=True, verbose_name='Dernier')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total', models.FloatField(default=0, verbose_name='Total sans TVA')),
                ('total_prix', models.FloatField(default=0, verbose_name='Total avec TVA')),
                ('reduction_categorie', models.CharField(blank=True, choices=[('', '----'), ('0', 'Remise'), ('1', 'Rabais'), ('2', 'Ristourne')], max_length=2, null=True)),
                ('reduction_type', models.CharField(blank=True, choices=[('', '----'), ('0', 'Pourcentage'), ('1', 'Argent')], max_length=2, null=True)),
                ('reduction', models.FloatField(default=0, verbose_name='Réduction')),
                ('negocie_ttc', models.BooleanField(default=False, verbose_name='Négocié en TTC')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons des commandes',
            },
        ),
        migrations.CreateModel(
            name='Facture_Offre_Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commande(Offres prépayée Partenaire)',
                'verbose_name_plural': 'Commandes(Offres prépayée Partenaire)',
            },
        ),
        migrations.CreateModel(
            name='Facture_OffrePrep_Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande(Offres prépayée Médecin)',
                'verbose_name_plural': 'Commandes(Offres prépayée Médecin)',
            },
        ),
        migrations.CreateModel(
            name='FactureCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default=core.models.increment_invoice_number, max_length=50, null=True)),
                ('numero_commande', models.CharField(blank=True, max_length=50, null=True)),
                ('first_last_name', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse')),
                ('numeros_telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('numeros_fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax ')),
                ('numero_registre_commerce', models.CharField(blank=True, max_length=50, null=True, verbose_name='NRC')),
                ('numero_identification_fiscale', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('numero_identification_domaine', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIC')),
                ('adresse_electronique', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Adresse éléctronique')),
                ('numero_article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Article N°')),
                ('numero_tin', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN N°')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut')),
                ('date_limite_reglement', models.DateField(blank=True, null=True)),
                ('mode_de_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de Paiement')),
                ('remises_et_rabais', models.FloatField(default=0, verbose_name='REMISES ET RABAIS')),
                ('frais_de_livraison', models.FloatField(default=0, verbose_name='FRAIS DE LIVRAISON')),
                ('timbre', models.FloatField(default=0, verbose_name='TIMBRE')),
                ('annuler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FactureCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation')),
                ('quantity', models.IntegerField(verbose_name='QTY')),
                ('montant', models.FloatField(default=0, verbose_name='PRIX HT')),
                ('pourcentage_tva', models.FloatField(default=0, verbose_name='Pourcentage TVA')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IbnHamzaFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
            ],
        ),
        migrations.CreateModel(
            name='Imagemodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/modules')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('a_installer', models.BooleanField(default=True)),
                ('a_desinstaller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_execution', models.DateTimeField(blank=True, null=True, verbose_name="Début d'exécution")),
                ('duree_reelle', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('rapport', tinymce.models.HTMLField(verbose_name="Rapport d'intervention")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clef', models.CharField(max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actiavtion_licence', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('num_ordre', models.CharField(blank=True, max_length=30, null=True, verbose_name="Numéro d'ordre")),
                ('num_agrement', models.CharField(blank=True, max_length=30, null=True, verbose_name="Numéro d'agrément")),
                ('date_derniere_connexion_web', models.DateTimeField(blank=True, null=True, verbose_name='Date de la dernière connexion web')),
                ('infos', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=0)),
                ('tarif_consultation_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('tarif_consultation', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='DZD', max_digits=14, null=True, verbose_name='Tarif de TéléConsultation')),
                ('tarif_cslt_cabinet_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('tarif_cslt_cabinet', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='DZD', max_digits=14, null=True, verbose_name='Tarif de Consultation Au Cabinet')),
                ('tarif_cslt_domicile_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('tarif_cslt_domicile', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='DZD', max_digits=14, null=True, verbose_name='Tarif de Consultation à domicile')),
                ('public_recu', models.CharField(blank=True, choices=[('1', 'Hommes Seulement'), ('2', 'Femmes Seulement')], max_length=2, null=True)),
                ('conventionne_chifa', models.BooleanField(default=False, verbose_name='Conventionné Chifa')),
                ('ccp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro CCP')),
                ('cle', models.CharField(blank=True, max_length=2, null=True, verbose_name='Clé')),
                ('bank_agence', models.CharField(blank=True, max_length=5, null=True, verbose_name='Agence')),
                ('bank_compte', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro du Compte')),
                ('bank_rib', models.CharField(blank=True, max_length=2, null=True, verbose_name='Clé RIB')),
                ('solde_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('solde', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=Decimal('0'), default_currency='DZD', max_digits=14, null=True, verbose_name='Solde')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bank')),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carteprofessionnelle')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('description_breve', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description Brève')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('unique_id', models.CharField(blank=True, help_text='is a unique identifier specified in the development phase ', max_length=255, null=True, verbose_name='Identificateur unique')),
                ('type_consomation', models.CharField(choices=[('1', 'DAILY'), ('2', 'WEEKLY'), ('3', 'MONTHLY'), ('4', 'QUARTERLY'), ('5', 'YEARLY')], max_length=10, verbose_name='Type de la consommation')),
                ('consomation', models.IntegerField(default=0, verbose_name='Consommation')),
                ('icon', models.ImageField(upload_to='uploads/icons_modules', verbose_name='Icône')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('captures_ecran', models.ManyToManyField(blank=True, to='core.Imagemodule', verbose_name="Captures d'écran")),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots clés')),
            ],
        ),
        migrations.CreateModel(
            name='OffrePartenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('consommation_affichage', models.IntegerField(verbose_name='Consomation par affichage en point')),
                ('consommation_clic', models.IntegerField(verbose_name='Consomation par clic en point')),
                ('points', models.IntegerField(verbose_name='Nb des point pack base')),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DZD', max_digits=14, verbose_name='valeur pack')),
                ('prix_point_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix_point', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='DZD', max_digits=14, verbose_name='Prix du point')),
            ],
            options={
                'verbose_name': 'Offre pour les partenaires',
                'verbose_name_plural': 'Offres pour les partenaire',
            },
        ),
        migrations.CreateModel(
            name='OffrePersonnalise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande(Offres personnalisée)',
                'verbose_name_plural': 'Commandes(Offres personnalisée)',
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('phone', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(blank=True, to='cities_light.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisonsocial', models.CharField(blank=True, max_length=255, null=True)),
                ('nrc', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(default=0)),
                ('logo', models.FileField(blank=True, null=True, upload_to='partenaires_logs')),
                ('banner', models.FileField(blank=True, null=True, upload_to='partenaires_banners')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('verifie', models.BooleanField(default=False, verbose_name='vérifié')),
                ('description', models.TextField(blank=True, null=True)),
                ('representantEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('representantNom', models.CharField(blank=True, max_length=255, null=True)),
                ('representantFct', models.CharField(blank=True, max_length=255, null=True)),
                ('representantEmail1', models.CharField(blank=True, max_length=255, null=True)),
                ('representantNom1', models.CharField(blank=True, max_length=255, null=True)),
                ('representantFct1', models.CharField(blank=True, max_length=255, null=True)),
                ('representantEmail2', models.CharField(blank=True, max_length=255, null=True)),
                ('representantNom2', models.CharField(blank=True, max_length=255, null=True)),
                ('representantFct2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.get_screenshot_path)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tarif', models.FloatField(verbose_name='Tarif')),
                ('nb_jours', models.IntegerField(blank=True, null=True, verbose_name='Nombre de jours')),
                ('creer_licence', models.BooleanField(default=False, verbose_name="Nécessité d'une licence")),
                ('besoin_licence', models.BooleanField(default=False, verbose_name="Besion d'une licence")),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFedilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('nb_points', models.IntegerField(blank=True, null=True, verbose_name='Nombre de points')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service de fédilité',
                'verbose_name_plural': 'Services de fédilité',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('libelle_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.IntegerField(blank=True, help_text='Points de catégorisation', null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='specialites')),
            ],
        ),
        migrations.CreateModel(
            name='Updater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='the accepted format is X.Y.Z.W', max_length=100, validators=[django.core.validators.RegexValidator('^(\\d+\\.)+(\\d+\\.)+(\\d+\\.)+(\\*|\\d+)$', code='invalid_version_number', message='Version number must be in the format X.Y.Z.W')])),
                ('last_version', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('zipfile', models.FileField(upload_to='updaters', validators=[core.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(storage=core.storage.CustomGoogleDriveStorage(), upload_to='annonces/videos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistredUser',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceDisplay',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.annonce')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.annonce',),
        ),
        migrations.CreateModel(
            name='AnnonceFeed',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.annonce')),
                ('titre', models.CharField(max_length=255)),
                ('corps', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.annonce',),
        ),
        migrations.CreateModel(
            name='AnnonceVideo',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.annonce')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.annonce',),
        ),
        migrations.CreateModel(
            name='AutreProduit',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence')),
                ('categorie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catégorie')),
                ('marque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque')),
                ('origine', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origine')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='DZD', max_digits=14, null=True, verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'Produit de type autre',
                'verbose_name_plural': 'Produits de type autre',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='CampagneImpression',
            fields=[
                ('campagne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.campagne')),
                ('reseaux', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'En Ligne'), (2, 'eTabib Workspace'), (3, 'Applications de eTabib'), (4, 'Applications mobile'), (5, 'Affichage CONGRES')], max_length=9)),
                ('toutes_specialites', models.BooleanField(default=False, verbose_name='Toutes les spécialités')),
                ('toutes_zones', models.BooleanField(default=False, verbose_name='Toutes les zones')),
                ('budget_max_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('budget_max', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='DZD', max_digits=14, null=True, verbose_name='Budget MAX')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.campagne',),
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('n_enregistrement', models.CharField(max_length=255, verbose_name="N° d'enregistrement")),
                ('type', models.CharField(choices=[('1', 'pharmaceutique'), ('2', 'parapharmaceutique')], default='1', max_length=2, verbose_name='Type')),
                ('indications', models.TextField(blank=True, help_text='les indications AMM de manière unitaire si possible selon le Standard en vigueur dans la langue du marché ', null=True, verbose_name='Indications')),
                ('remboursement', models.BooleanField(default=False, help_text="l'etat de remboursement ", verbose_name='Remboursable')),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='DZD', max_digits=14, null=True, verbose_name='Prix public')),
                ('fabriquant', models.CharField(blank=True, max_length=255, null=True)),
                ('exploitant', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_etude', models.URLField(blank=True, help_text="Lien de l'étude de référence", null=True, verbose_name='Étude de référence')),
            ],
            options={
                'verbose_name': 'Produit de type médicament /parapharmacie',
                'verbose_name_plural': 'Produits de type médicament /parapharmacie',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('n_enregistrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="N° d'enregistrement")),
                ('description', models.TextField(verbose_name='Description')),
                ('marque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque')),
                ('origine', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origine')),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='DZD', max_digits=14, null=True, verbose_name='Prix')),
                ('promotion', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Promotion')),
                ('fin_promotion', models.DateTimeField(blank=True, null=True, verbose_name='Fin de promotion')),
            ],
            options={
                'verbose_name': 'Produit de type dispositif médical',
                'verbose_name_plural': 'Produits de type dispositif médical',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/virements')),
                ('date_creation', models.DateTimeField(verbose_name="Date d'ajout")),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('methode_paiement', models.CharField(blank=True, choices=[('1', 'ESPECE'), ('2', 'TPE'), ('3', 'VIRMENT CCP SOCIETE'), ('4', 'VIRMENT CCP RESPONSABLE'), ('5', 'VIRMENT BANCAIRE'), ('6', 'EPAIEMENT'), ('7', 'Chèque')], max_length=2, null=True)),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence')),
                ('verifie', models.BooleanField(default=True)),
                ('ajouter_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='the accepted format is X.Y.Z', max_length=10, validators=[django.core.validators.RegexValidator('^(\\d+\\.)+(\\d+\\.)+(\\*|\\d+)$', code='invalid_version_number', message='Version number must be in the format X.Y.Z')], verbose_name='Numéro de version')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lastversion', models.BooleanField(default=False, verbose_name='Dernière version')),
                ('zipfile', models.FileField(upload_to='uploads/versions/%Y/%m/%d/', validators=[core.models.validate_file_extension], verbose_name='Le fichier zip')),
                ('compatible_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etabib_set', to='core.etabib', verbose_name='Version Etabib Compatible')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.module', verbose_name='Module')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User agent')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip address')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message')),
                ('termine', models.BooleanField(default=False, verbose_name='Terminée')),
                ('attribuee_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tach_attr_set', to='core.operateur', verbose_name='Attribuée à')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contact')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tach_cree_par_set', to='core.operateur', verbose_name='Crée par')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('urgent', models.BooleanField(default=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operateur', verbose_name='Crée par')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signaletique', models.CharField(max_length=255, verbose_name='Signalétique')),
                ('slogan', models.CharField(max_length=55, verbose_name='Slogan')),
                ('banner', models.ImageField(default='HABILLAGE_STAND_DEFAULT.png', help_text="L'image doit avoir une largeur de 1600px et une hauteur de 840px, avec une taille < 2Mb", upload_to='stand/%Y/%m/%d/', validators=[core.models.stand_validate_image])),
                ('link', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Lien vidéo')),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('salle_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la salle de discussion')),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe')),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('urgent', models.BooleanField(default=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operateur', verbose_name='Crée par')),
                ('liste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listeprospect', verbose_name='Liste')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.IntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionnelSante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carteprofessionnelle')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professionnel(le) de santé',
                'verbose_name_plural': 'Professionnel(le)s de santé',
            },
        ),
        migrations.CreateModel(
            name='ProchaineRencontre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rencontre', models.DateField(verbose_name='Rencontrer dans')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('detail_action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.detailaction')),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('descreption', tinymce.models.HTMLField(verbose_name='Description')),
                ('solution', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Solution')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operateur')),
                ('screenshot', models.ManyToManyField(blank=True, to='core.Screenshot', verbose_name="Captures d'écran")),
            ],
        ),
        migrations.CreateModel(
            name='PrecommandeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.article')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('mac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifiant unique')),
                ('old_mac', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ancien Identifiant unique')),
                ('sid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifiant de sécurité')),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Date de la dernière connexion')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('desactive_apps', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('etabibappliction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.etabib')),
                ('eula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.eula')),
                ('licence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.licence')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='core.medecin', verbose_name='Médecin')),
                ('modules', models.ManyToManyField(blank=True, through='core.Installation', to='core.Version')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.updater')),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partenaire')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poste')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Crée par')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('1', 'HOMME'), ('2', 'FEMME')], max_length=2, null=True, verbose_name='Sexe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone')),
                ('solde_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('solde', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=Decimal('0'), default_currency='DZD', max_digits=14, null=True, verbose_name='Solde')),
                ('num_carte_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° carte Nationale')),
                ('nin', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° national')),
                ('chifa', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° carte chifa')),
                ('donnees_medicales', models.JSONField(default=dict, verbose_name='Donnée Médicales')),
                ('carte_chifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carte_chifa', to='core.carteid', verbose_name='Carte Chifa')),
                ('carte_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carte_id', to='core.carteid', verbose_name="Carte d'Identité")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_set', to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country', verbose_name='Pays')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city', verbose_name='Ville')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.region', verbose_name='Wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='PartenaireMarque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='trademark_logos')),
                ('designation', models.CharField(blank=True, max_length=2, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partenaire', verbose_name='Partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='OffrePrepaye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('points', models.IntegerField(verbose_name='Quantité de points')),
                ('prix_unite', models.IntegerField(verbose_name="Prix unitaire d'un point")),
                ('reduction_intervention', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Pourcentage de réduction pour les interventions')),
                ('reduction_achat_points', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name="Pourcentage de réduction pour l'achat des points")),
                ('reduction_modules', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name="Pourcentage de réduction pour l'utilisations des modules")),
                ('licences_nbjours', models.IntegerField(help_text="Pour l'illimité vous mettez 0", verbose_name='Nombre de jours de la licence')),
                ('licences_nbjours_desc', models.CharField(blank=True, help_text='Utilisé dans la page des offres', max_length=200, null=True, verbose_name="Durée d'abonnement (text)")),
                ('prix', models.IntegerField(blank=True, help_text='en dinar algérien', null=True, verbose_name="Prix de l'offre")),
                ('prix_reduit', models.IntegerField(blank=True, help_text='en dinar algérien', null=True, verbose_name="Prix de l'offre(Réduit)")),
                ('critere_reduction', models.CharField(blank=True, choices=[('1', 'Délai 15 jours aprés la validation')], max_length=3, null=True, verbose_name='Critère de réduction')),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'eTabib Workspace'), ('2', 'Agenda en ligne'), ('3', 'eTabib Care'), ('4', 'eTabib visio'), ('5', 'eTabib Store'), ('6', 'Ordonnancier digital'), ('7', 'etabib Annuaire'), ('8', 'Télécharger Les Applis eTabib® Store'), ('9', 'Clinique virtuelle')], default=('1', '2', '3'), max_length=50)),
                ('sav', models.CharField(blank=True, choices=[('1', 'BASE'), ('2', 'PRO'), ('3', 'PREMIUM')], max_length=3, null=True, verbose_name='Support/SAV')),
                ('avantages', models.ManyToManyField(blank=True, to='core.ServiceFedilite', verbose_name='Services de fidélité')),
            ],
            options={
                'verbose_name': 'Offre prépayée pour les médecins',
                'verbose_name_plural': 'Offres prépayées pour les médecins',
            },
        ),
        migrations.CreateModel(
            name='OffrePersonnalise_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('reduction', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offre_perso_licence_set', to='core.licence')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offrepersonnalise')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offre_perso_service_set', to='core.service')),
            ],
        ),
        migrations.AddField(
            model_name='offrepersonnalise',
            name='avantages',
            field=models.ManyToManyField(blank=True, to='core.ServiceFedilite'),
        ),
        migrations.AddField(
            model_name='offrepersonnalise',
            name='services',
            field=models.ManyToManyField(through='core.OffrePersonnalise_Service', to='core.Service'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('valeur', models.DecimalField(decimal_places=1, max_digits=3)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medecin')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.module')),
            ],
            options={
                'verbose_name': 'Note sur les modules',
                'verbose_name_plural': 'Notes sur les modules',
            },
        ),
    ]
