# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('cities_light', '0010_auto_20200508_1851'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('epayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeprospect',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.ville', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='listeprospect',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liste_prospect', to='core.operateur', verbose_name='Crée par'),
        ),
        migrations.AddField(
            model_name='listeprospect',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.specialite', verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='licence',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='detail_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.detailaction'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='probleme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.probleme', verbose_name='Problème'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='core.Screenshot', verbose_name="Captures d'écran"),
        ),
        migrations.AddField(
            model_name='installation',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poste'),
        ),
        migrations.AddField(
            model_name='installation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.version'),
        ),
        migrations.AddField(
            model_name='facturecompanydetail',
            name='facturecompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_company_detail', to='core.facturecompany'),
        ),
        migrations.AddField(
            model_name='facturecompany',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture_offreprep_licence',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fol_facture_set', to='core.facture'),
        ),
        migrations.AddField(
            model_name='facture_offreprep_licence',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fol_licensce_set', to='core.licence'),
        ),
        migrations.AddField(
            model_name='facture_offreprep_licence',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offreprepaye'),
        ),
        migrations.AddField(
            model_name='facture_offre_partenaire',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fop_facture_set', to='core.facture'),
        ),
        migrations.AddField(
            model_name='facture_offre_partenaire',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offrepartenaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='facture',
            name='detail_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.detailaction'),
        ),
        migrations.AddField(
            model_name='facture',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medecin'),
        ),
        migrations.AddField(
            model_name='facture',
            name='offre_perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_pers_set', to='core.offrepersonnalise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='ordre_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='epayment.ordredepaiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.poste'),
        ),
        migrations.AddField(
            model_name='equipesoins',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_soins', to='core.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='equipesoins',
            name='professionnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professionnel(le) de santé'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_set', to='core.action'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.detailactionaudiofile', verbose_name='Fichier son'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operateur'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.detailactionfile', verbose_name='Pièce jointe'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.action'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.demandeinterventionimage'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poste'),
        ),
        migrations.AddField(
            model_name='contact',
            name='agrement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_agrement_certificat', to='core.certificat', verbose_name='Autorisation de travail (agrément ou certificat de travail)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operateur', verbose_name='Crée par'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='contact',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='core.Qualification', verbose_name='Qualifications'),
        ),
        migrations.AddField(
            model_name='contact',
            name='qualifications_certificats',
            field=models.ManyToManyField(blank=True, related_name='contact_qualifications_certificats', to='core.Certificat', verbose_name='Qualifications Certificats'),
        ),
        migrations.AddField(
            model_name='contact',
            name='rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='contact',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.specialite', verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='specialite_certificat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_specialite_certificat', to='core.certificat', verbose_name='Spécialité certificat'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medecin'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.module'),
        ),
        migrations.AddField(
            model_name='clotureaction',
            name='detail_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.detailaction'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='campagnestatistique',
            name='campagne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campagne'),
        ),
        migrations.AddField(
            model_name='campagnestatistique',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poste'),
        ),
        migrations.AddField(
            model_name='campagnestatistique',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campagne',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.campagne_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='article',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.article_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='annonceimpressionlog',
            name='annonce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.annonce', verbose_name='Annonce'),
        ),
        migrations.AddField(
            model_name='annonceimpressionlog',
            name='campagne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campagne', verbose_name='Campagne'),
        ),
        migrations.AddField(
            model_name='annonceimpressionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annoncefeedback',
            name='annonce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.annonce', verbose_name='Annonce'),
        ),
        migrations.AddField(
            model_name='annoncefeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonceclicklog',
            name='annonce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.annonce', verbose_name='Annonce'),
        ),
        migrations.AddField(
            model_name='annonceclicklog',
            name='campagne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campagne', verbose_name='Campagne'),
        ),
        migrations.AddField(
            model_name='annonceclicklog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partenaire'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.annonce_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='action',
            name='attribuee_a_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='action',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='action',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operateur_cree_set', to='core.operateur', verbose_name='Créé par'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'permissions': (('can_view_client_list', 'Can view client list'),),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorieproduit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='document_aut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_aut_prd_set', to='core.articledocument', verbose_name="Document pour l'autorisation"),
        ),
        migrations.AddField(
            model_name='produit',
            name='document_hom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_hom_prd_set', to='core.articledocument', verbose_name="Document pour l'homologation"),
        ),
    ]
