# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('cities_light', '0010_auto_20200508_1851'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='dci',
            field=models.ForeignKey(help_text='le DCI selon La nomenclature ATC', on_delete=django.db.models.deletion.CASCADE, related_name='dci_medic_set', to='drugs.dciatc', verbose_name='DCI'),
        ),
        migrations.AddField(
            model_name='medic',
            name='document_aut_amm',
            field=models.ForeignKey(blank=True, help_text="Un Document attestant l'autorisation AMM du marché concerné si le Médicament ne figure pas sur la liste du Régulateur ", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_aut_amm_medic_set', to='core.articledocument', verbose_name="Document attestant l'autorisation AMM"),
        ),
        migrations.AddField(
            model_name='medic',
            name='interactions',
            field=models.ManyToManyField(blank=True, related_name='interactions_medic_set', to='drugs.DciAtc', verbose_name='Intéractions'),
        ),
        migrations.AddField(
            model_name='medic',
            name='rcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcp_medic_set', to='core.articledocument', verbose_name='RCP'),
        ),
        migrations.AlterUniqueTogether(
            name='equipesoins',
            unique_together={('patient', 'professionnel')},
        ),
        migrations.AddField(
            model_name='campagneimpression',
            name='annonces',
            field=models.ManyToManyField(to='core.Annonce'),
        ),
        migrations.AddField(
            model_name='campagneimpression',
            name='cibles',
            field=models.ManyToManyField(blank=True, to='core.Specialite'),
        ),
        migrations.AddField(
            model_name='campagneimpression',
            name='zones',
            field=models.ManyToManyField(blank=True, to='cities_light.Region'),
        ),
        migrations.AddField(
            model_name='annoncevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video'),
        ),
        migrations.AddField(
            model_name='annoncedisplay',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.AnnonceImage'),
        ),
    ]
