# Generated by Django 3.2.9 on 2023-04-07 07:39

import core.mime_types
import core.models
import core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonceimage',
            name='image',
            field=models.ImageField(upload_to=core.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='articledocument',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'pdf']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='produits/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='bddscript',
            name='zipfile',
            field=models.FileField(upload_to='bddscripts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='carteid',
            name='image_arriere',
            field=models.ImageField(blank=True, default='default_pile_card_id.png', null=True, upload_to=core.models.get_carteid_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='carteid',
            name='image_avant',
            field=models.ImageField(blank=True, default='default_face_card_id.png', null=True, upload_to=core.models.get_carteid_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='carteprofessionnelle',
            name='image',
            field=models.ImageField(default='default_card.png', upload_to='cartes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='image',
            field=models.ImageField(help_text="L'image doit avoir une largeur de 840px et une hauteur de 1120px, avec une taille < 2Mb", upload_to='catalogue', validators=[core.models.validate_image, core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='file',
            field=models.FileField(upload_to='certificat/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'pdf']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='carte',
            field=models.FileField(blank=True, null=True, upload_to='cartes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'pdf']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='demandeinterventionimage',
            name='image',
            field=models.ImageField(upload_to='demande_intervention/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='detailactionaudiofile',
            name='file',
            field=models.FileField(upload_to='action/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='detailactionfile',
            name='file',
            field=models.FileField(upload_to='action/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'pdf']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='etabib',
            name='zipfile',
            field=models.FileField(upload_to='etabib', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='imagemodule',
            name='image',
            field=models.ImageField(upload_to='uploads/modules', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.ImageField(upload_to='uploads/icons_modules', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'ico']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'ico'])], verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires_banners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires_logs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='partenairemarque',
            name='image',
            field=models.ImageField(upload_to='trademark_logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=core.models.get_screenshot_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specialites', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='stand',
            name='banner',
            field=models.ImageField(default='HABILLAGE_STAND_DEFAULT.png', help_text="L'image doit avoir une largeur de 1600px et une hauteur de 840px, avec une taille < 2Mb", upload_to='stand/%Y/%m/%d/', validators=[core.models.stand_validate_image, core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='updater',
            name='zipfile',
            field=models.FileField(upload_to='updaters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='version',
            name='zipfile',
            field=models.FileField(upload_to='uploads/versions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['zip'])], verbose_name='Le fichier zip'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fichier',
            field=models.FileField(storage=core.storage.CustomGoogleDriveStorage(), upload_to='annonces/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['mp4', 'avi', 'mpeg'])]),
        ),
        migrations.AlterField(
            model_name='virement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/virements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
