# Generated by Django 3.2.9 on 2024-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230407_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='annonce',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagne',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagne',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
