# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operateur', verbose_name='Crée par')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.offreprepaye')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country', verbose_name='Pays')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.specialite', verbose_name='Spécialité')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city', verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('message', models.CharField(max_length=160, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g: 'welcome_sms'", max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this template.', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('content', models.TextField(blank=True, max_length=160, verbose_name='Content')),
                ('language', models.CharField(blank=True, default='', help_text='Render template in alternative language', max_length=12, verbose_name='Language')),
                ('default_template', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_templates', to='smsgateway.smstemplate', verbose_name='Default template')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'language', 'default_template')},
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default='2')),
                ('message', models.CharField(blank=True, max_length=160, null=True, verbose_name='Message')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'TOSEND'), ('2', 'SENT'), ('3', 'DELIVERED'), ('4', 'RECEIVED')], default='1', max_length=255, verbose_name='Status')),
                ('sim', models.CharField(choices=[('1', 'Sim1'), ('2', 'Sim2')], default='1', max_length=255, verbose_name='Sim')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contact', verbose_name='Contact')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operateur')),
                ('critere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smsgateway.critere', verbose_name='Critere')),
                ('smsmodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smsgateway.smsmodel', verbose_name='SmsModel')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smsgateway.smstemplate', verbose_name='SmsTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Listenvoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, to='core.Contact')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operateur', verbose_name='Crée par')),
            ],
        ),
    ]
