from django.conf.urls import url
from django.urls import path

from crm.views import contact_views, dashboard_views, agenda_views, task_views, tech_views, offer_views, views, \
    order_views

urlpatterns = [
    # operator urls
    url(r'^operator/contact/list/$', contact_views.ContactDatatableView.as_view(), name='operator-list-contact'),
    url(r'^operator/contact/list/simplified/$', contact_views.ContactListView.as_view(),
        name='operator-list-contact-simplified'),
    url(r'^operator/contact/add/$', contact_views.addContact, name='operator-add-contact'),
    url(r'^operator/contact/edit/(?P<pk>\d+)/$', contact_views.editContact, name='operator-edit-contact'),
    url(r'^operator/contact/(?P<pk>\d+)/$', contact_views.ContactDetailView.as_view(), name='operator-detail-contact'),
    path('operator/contact/ajax', contact_views.ContactAjaxDatatableView.as_view(), name='contact_ajax'),
    url(r'^operator/contact/filter/$', contact_views.filter_contacts, name='operator-filter-contacts'),
    path('operator/commande/create', order_views.create_untreated_commande, name='commande_create'),
    path('operator/commande/list', order_views.UntreatedCommandeListView.as_view(), name='commande_list'),
    path('operator/commande/ajax', order_views.UntreatedCommandeAjaxDatatableView.as_view(), name='commande_ajax'),
    path('operator/bordereau/list', order_views.BordereauListView.as_view(), name='bordereau_list'),
    path('operator/bordereau/ajax', order_views.BordereauAjaxDatatableView.as_view(), name='bordereau_ajax'),
    path('operator/generate_bordereau', order_views.generate_bordereau, name='generate_bordereau'),
    url(r'^operator/archive/(?P<pk>\d+)/$', contact_views.ArchiveContactView.as_view(),
        name='operator-archive-contact'),
    url(r'^operator/monitoring/list/$', contact_views.ListeSuiviDatatableView.as_view(),
        name='operator-monitoring-list'),
    url(r'operator/commande/confirme/(?P<contact_pk>\d+)/(?P<commande_pk>\d+)/(?P<action_pk>\d+)/$',
        offer_views.createOrderDirectly, name='commande_confirme'),
    url(r'operator/commande/confirme/(?P<contact_pk>\d+)/(?P<commande_pk>\d+)/$',
        offer_views.createOrderDirectly, name='commande_confirme_q'),

    # Communication Urls
    url(r'^operator/dashboard/$', dashboard_views.dashboard, name='operator-dashboard'),
    url(r'^operator/events/$', agenda_views.events, name='operator-events'),
    url(r'^operator/events/expired/$', agenda_views.ExpiredEventDatatableView.as_view(),
        name='communication-expired-events'),
    url(r'^operator/fetchevents/$', agenda_views.fetchEvents, name='operator-fetch-events'),
    url(r'^operator/event/update$', agenda_views.updateEvent, name='operator-update-event'),

    # Administrator Urls
    url(r'^operator/task/list/$', task_views.TaskDatatableAdmView.as_view(), name='operator-task-list'),
    url(r'^operator/task/create/$', task_views.TaskَCreateView.as_view(), name='operator-create-task'),
    url(r'^operator/task/update/(?P<pk>\d+)/$', task_views.TaskUpdateView.as_view(), name='operator-update-task'),
    url(r'^operator/task/delete/(?P<pk>\d+)/$', task_views.TaskDeleteView.as_view(), name='operator-delete-task'),

    # Technician Urls
    url(r'^operator/intervention/create/(?P<action_pk>\d+)/$', tech_views.InterventionCreateView.as_view(),
        name='technician-create-intervention'),
    url(r'^operator/intervention/update/(?P<pk>\d+)/$', tech_views.InterventionUpdateView.as_view(),
        name='technician-update-intervention'),
    url(r'^operator/problem/list/$', tech_views.ProblemDatatableView.as_view(),
        name='technician-list-problem'),
    url(r'^operator/problem/create/$', tech_views.ProblemَCreateView.as_view(),
        name='technician-create-problem'),
    url(r'^operator/problem/update/(?P<pk>\d+)/$', tech_views.ProblemUpdateView.as_view(),
        name='technician-update-problem'),
    url(r'^operator/problem/delete/(?P<pk>\d+)/$', tech_views.ProblemDeleteView.as_view(),
        name='technician-delete-problem'),

    # Commercial Urls
    url(r'^operator/invoice/load$', offer_views.loadInvoice, name='commercial-invoice-load'),
    url(r'^offer/list$', offer_views.listPrepaidOffer, name='list-prep-offer'),
    url(r'^offer/partner/list$', offer_views.listPartnerOffer, name='list-partn-offer'),
    url(r'^offer/detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', offer_views.detailOffer, name='detail-offer'),
    url(r'^offer/partner/detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', offer_views.detailOfferPartner,
        name='detail-offer-partner'),
    url(r'^operator/order/create/(?P<action_pk>\d+)/$', offer_views.createOrder, name='commercial-create-order'),
    url(r'^operator/order/partner/create/(?P<action_pk>\d+)/$', offer_views.createPartnerOrder,
        name='commercial-create-partner-order'),
    url(r'^operator/custom-order/create/(?P<action_pk>\d+)/$', offer_views.createCustomOrder,
        name='commercial-create-custom-order'),
    url(r'^order/detail/(?P<pk>\d+)/$', offer_views.detailOrder, name='detail-order'),
    url(r'^operator/order/list/$', offer_views.OrderDatatableView.as_view(), name='commercial-list-order'),
    url(r'^operator/order/list/(?P<medecin_id>\d+)/$', offer_views.OrderDatatableView.as_view(),
        name='commercial-list-order-by-medecin'),
    url(r'^operator/order/update/(?P<pk>\d+)/$', offer_views.OrderUpdateView.as_view(),
        name='commercial-update-order'),
    url(r'^operator/order/delete/(?P<pk>\d+)/$', offer_views.OrderDeleteView.as_view(),
        name='commercial-delete-order'),
    url(r'^operator/virement/list/$', offer_views.VirementDatatableView.as_view(),
        name='commercial-list-virement'),
    url(r'^operator/virement/create/$', offer_views.VirementCreateView.as_view(),
        name='commercial-create-virement'),
    url(r'^operator/virement/update/(?P<pk>\d+)/$', offer_views.VirementUpdateView.as_view(),
        name='commercial-update-virement'),
    url(r'^operator/virement/delete/(?P<pk>\d+)/$', offer_views.VirementDeleteView.as_view(),
        name='commercial-delete-virement'),
    url(r'^operator/invoice/list/$', offer_views.InvoiceDatatableView.as_view(), name='commercial-list-invoice'),
    url(r'^operator/invoice/create/(?P<pk>\d+)/$', offer_views.createInvoice, name="invoice-create"),
    url(r'^operator/invoice/anuler/(?P<pk>\d+)/$', offer_views.InvoiceUpdateView.as_view(),
        name="invoice-annuler"),
    url(r'^operator/invoice/detail/(?P<pk>\d+)/$', offer_views.detailInvoice, name='invoice-detail'),
    url(r'^operator/invoice/print/(?P<pk>\d+)/$', offer_views.invoice_as_pdf, name='commercial-print-invoice'),

    url(r'^operator/order/service/assign/$', offer_views.AssignServiceView.as_view(),
        name='commercial-assign-service'),
    url(r'^operator/piste/create/(?P<contact_pk>\d+)/$', agenda_views.PisteCreateView.as_view(),
        name='commercial-create-piste'),
    url(r'^operator/piste/bulk/create/(?P<list_pk>\d+)/$', agenda_views.PisteBulkCreateView.as_view(),
        name='commercial-create-piste-bulk'),
    url(r'^operator/piste/list/(?P<contact_pk>\d+)/$', agenda_views.PisteDatatableView.as_view(),
        name='commercial-list-piste'),
    url(r'^operator/detail/piste/create/(?P<action_id>\d+)/$', agenda_views.DetailPisteCreateView.as_view(),
        name='create-detail-piste'),
    url(r'^operator/meeting/create/(?P<action_id>\d+)/$', agenda_views.ProchaineRencontreCreateView.as_view(),
        name='create-meeting-piste'),
    url(r'^operator/meeting/update/(?P<pk>\d+)/(?P<action_id>\d+)/$',
        agenda_views.ProchaineRencontreUpdateView.as_view(),
        name='update-meeting-piste'),
    url(r'^operator/nextmeeting/treat/(?P<pk>\d+)/$', agenda_views.TreatProchaineRencontreView.as_view(),
        name='treat-meeting-piste'),
    url(r'^operator/piste/closing/(?P<action_id>\d+)/$', agenda_views.ClotureActionFormCreateView.as_view(),
        name='create-closing-piste'),
    url(r'^operator/piste/extend/(?P<pk>\d+)/$', agenda_views.ProlongerPisteFormCreateView.as_view(),
        name='extend-piste'),
    url(r'^operator/prospect/add/(?P<contact_pk>\d+)/$', agenda_views.ProspectCreateView.as_view(),
        name='commercial-add-prospect'),
    url(r'^operator/prospect/list/create$', agenda_views.create_prospect_list, name='operator-prospect-list-create'),
    url(r'^operator/prospect/list/$', agenda_views.ProspectListDatatableView.as_view(), name='commercial-list-prospect'),
    url(r'^operator/prospect/list/detail/(?P<list_id>\d+)$', agenda_views.ProspectDatatableView.as_view(), name='commercial-list-prospect-detail'),
    url(r'^operator/prospect/delete/(?P<pk>\d+)/$', agenda_views.ProspectDeleteView.as_view(),
        name='commercial-delete-prospect'),
    url(r'^operator/prospect/list/delete/(?P<pk>\d+)/$', agenda_views.ProspectListDeleteView.as_view(),
        name='commercial-delete-prospect-list'),
    url(r'^operator/task/done/$', task_views.markTaskAsDone, name='operator-task-done'),
    url(r'^operator/account/create/(?P<action_id>\d+)/$', agenda_views.createAccount,
        name='commercial-account-create'),

    # Action Urls
    url(r'^action/(?P<pk>\d+)/$', agenda_views.ActionَDetailView.as_view(), name='action-detail'),
    url(r'^action/update/(?P<pk>\d+)/$', agenda_views.ActionUpdateView.as_view(), name='update-action'),
    url(r'^action/inactivate/(?P<pk>\d+)/$', agenda_views.InactivateActionView.as_view(), name='inactivate-action'),
    url(r'^action/create/$', agenda_views.ActionCreateView.as_view(), name='create-action'),
    url(r'^action/create/(?P<contact_pk>\d+)/$', agenda_views.ActionCreateView.as_view(), name='create-action-contact'),
    url(r'^action/create/(?P<contact_pk>\d+)/(?P<type_action>\d+)/$', agenda_views.ActionCreateView.as_view(),
        name='create-action-contact-type'),
    url(r'^action/create/(?P<contact_pk>\d+)/(?P<type_action>\d+)/(?P<oper_pk>\d+)/$',
        agenda_views.ActionCreateView.as_view(), name='create-action-contact-type-oper'),
    url(r'^detail/action/update/(?P<pk>\d+)/(?P<action_id>\d+)/$', agenda_views.DetailActionUpdateView.as_view(),
        name='update-detail-action'),
    url(r'^detail/action/delete/(?P<pk>\d+)/$', agenda_views.DetailActionDeleteView.as_view(),
        name='delete-detail-action'),

    # Common Utrls
    url(r'^pin-board/$', views.PinBoardListView.as_view(), name='pin-board'),
    url(r'^pin-board/create/$', views.PinBoardCreateView.as_view(), name='pin-board-add'),
    url(r'^pin-board/delete/(?P<pk>\d+)/$', views.PinBoardDeleteView.as_view(), name='pin-board-delete'),
    url(r'^intervention/(?P<pk>\d+)/$', tech_views.demandeInterventionDetail, name='demande-intervention-detail'),
    url(r'^intervention/action/create/(?P<contact_pk>\d+)/(?P<type_action>\d+)/(?P<dmnd_interv_pk>\d+)$',
        agenda_views.ActionCreateView.as_view(),
        name='create-action-from-demannd-intervention'),
    url(r'^eula/$', views.eula, name='eula'),
    url(r'^task/list$', task_views.TaskDatatableView.as_view(), name='task-list'),
    url(r'^verify-email/$', contact_views.verify_email, name='verify-email'),

    # Upload Utrls
    url(r'^detail-action-file-upload/$', agenda_views.detailActionFileUpload, name='detail-action-file-upload'),
    url(r'^detail-action-audio-file-upload/$', agenda_views.detailActionAudioFileUpload,
        name='detail-action-audio-file-upload'),
    url(r'^screenshot-upload/$', tech_views.screenShotUpload, name='screenshot-upload'),
    url(r'^commande-upload-image/$', order_views.upload_commande_image, name='upload-commande-image'),
]
