from django.conf.urls import url
from django.views.generic import TemplateView

from ads.views import partner_views
from core import autocomplete

urlpatterns = [
    url(r'^partner/register/$', partner_views.registerPartner, name='partner-registration'),
    url(r'^partner/dashboard/$', partner_views.dashboard, name='partner-dashboard'),
    url(r'^partner/profile/$', partner_views.profile, name='partner-profile'),
    url(r'^partner/validate/$', TemplateView.as_view(template_name='partner/acount_validation.html'),
        name='partner-account-validation'),
    url(r'^categorie-produit-autocomplet/$', autocomplete.CategorieProduitAutocomplete.as_view(create_field='titre_fr'),
        name='categorie-produit-autocomplet'),
    url(r'^partner/product/list/$', partner_views.ArticleDatatableView.as_view(), name='partner-list-product'),
    url(r'^partner/product/create/$', partner_views.ProductCreateView.as_view(), name='partner-create-product'),
    url(r'^partner/product/delete/(?P<pk>\d+)/$', partner_views.ArticleDeleteView.as_view(),
        name='partner-delete-product'),
    url(r'^partner/product/update/(?P<pk>\d+)/$', partner_views.ProductUpdateView.as_view(),
        name='partner-update-product'),
    url(r'^partner/product/item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', partner_views.ArticleDetailView.as_view(),
        name='partner-detail-product'),
    url(r'^partner/drug/create/$', partner_views.DrugCreateView.as_view(), name='partner-create-drug'),
    url(r'^partner/drug/update/(?P<pk>\d+)/$', partner_views.DrugUpdateView.as_view(), name='partner-update-drug'),
    url(r'^partner/oproduct/create/$', partner_views.OtherProductَCreateView.as_view(),
        name='partner-create-other-product'),
    url(r'^partner/oproduct/update/(?P<pk>\d+)/$', partner_views.OtherProductUpdateView.as_view(),
        name='partner-update-other-product'),
    url(r'^partner/ad/list/$', partner_views.AnnonceDatatableView.as_view(), name='partner-list-ads'),
    url(r'^partner/ad/delete/(?P<pk>\d+)/$', partner_views.AnnonceDeleteView.as_view(), name='partner-delete-ads'),
    url(r'^partner/ad/feed/create/$', partner_views.AnnonceFeedَCreateView.as_view(), name='partner-create-ads-feed'),
    url(r'^partner/ad/feed/update/(?P<pk>\d+)/$', partner_views.AnnonceFeedUpdateView.as_view(),
        name='partner-update-ads-feed'),
    url(r'^partner/ad/display/create/$', partner_views.AnnonceDisplayَCreateView.as_view(),
        name='partner-create-ads-display'),
    url(r'^partner/ad/display/update/(?P<pk>\d+)/$', partner_views.AnnonceDisplayUpdateView.as_view(),
        name='partner-update-ads-display'),
    url(r'^partner/ad/item/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', partner_views.AnnonceDetailView.as_view(),
        name='partner-detail-ads'),
    url(r'^partner/ad/video/update/(?P<pk>\d+)/$', partner_views.AnnonceVideoUpdateView.as_view(),
        name='partner-update-ads-video'),
    url(r'^partner/ad/video/create/$', partner_views.AnnonceVideoَCreateView.as_view(),
        name='partner-create-ads-video'),
    url(r'^partner/campaign/list/$', partner_views.CampaignDatatableView.as_view(), name='partner-list-campaign'),
    url(r'^partner/campaign/delete/(?P<pk>\d+)/$', partner_views.CampagneDeleteView.as_view(),
        name='partner-delete-campaign'),
    url(r'^partner/campaign/imp/create/$', partner_views.CampagneImpَCreateView.as_view(),
        name='partner-create-campaign-imp'),
    url(r'^partner/campaign/imp/update/(?P<pk>\d+)/$', partner_views.CampagneImpUpdateView.as_view(),
        name='partner-update-campaign-imp'),
    url(r'^partner/campaign/imp/activate/(?P<pk>\d+)/$', partner_views.CampagneImpActivateView.as_view(),
        name='partner-activate-campaign-imp'),
    url(r'^partner/campaign/item/(?P<pk>\d+)/$', partner_views.CampagneDetailView.as_view(),
        name='partner-detail-campaign'),
    url(r'^partner/campaign/imp/cancel/(?P<pk>\d+)/$', partner_views.CampagneImpCancelView.as_view(),
        name='partner-cancel-campaign-imp'),
    url(r'^partner/campaign/imp/stop/(?P<pk>\d+)/$', partner_views.CampagneImpStopView.as_view(),
        name='partner-stop-campaign-imp'),
    url(r'^partner/campaign/stats/(?P<pk>\d+)/$', partner_views.campaignStats, name='partner-campaign-stats'),
    url(r'^partner/points/history/$', partner_views.pointsHistory, name='partner-points-history'),
    url(r'^partner/campaign/stats/gather/$', partner_views.campaignStatsByAnnonce, name='partner-campaign-stats-by-ad'),
    url(r'^partner/catalogue/list/', partner_views.catalogueList, name='partner-list-catalogue'),
    url(r'^partner/catalogue/create/$', partner_views.CatalogueCreateView.as_view(), name='partner-create-catalogue'),
    url(r'^partner/catalgue/update/(?P<pk>\d+)/$', partner_views.CatalogueUpdateView.as_view(),
        name='partner-update-catalogue'),
    url(r'^partner/catalgue/delete/(?P<pk>\d+)/$', partner_views.CatalogueDeleteView.as_view(),
        name='partner-delete-catalogue'),
    url(r'^partner/stand/$', partner_views.myStand, name='partner-stand'),
    url(r'^partner/precommandes/$', partner_views.PrecommandeDatatableView.as_view(), name='partner-precommandes'),

    #upload urls
    url(r'^product-image-upload/$', partner_views.articleImageUpload, name='product-image-upload'),
    url(r'^product-document-upload/$', partner_views.articleDocumentUpload, name='product-document-upload'),
    url(r'^annonce-image-upload/$', partner_views.adsImageUpload, name='annonce-image-upload'),
    url(r'^annonce-video-upload/$', partner_views.adsVideoUpload, name='annonce-video-upload'),
    url(r'^logo-trademark-upload/$', partner_views.logo_trademark_upload, name='logo-trademark-upload'),
]
