# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('1', 'En ligne'), ('2', 'À domicile'), ('3', 'Au cabinet')], default='1', max_length=2)),
                ('acceptee', models.BooleanField(default=False)),
                ('refusee', models.BooleanField(default=False)),
                ('annulee', models.BooleanField(default=False)),
                ('gratuit', models.BooleanField(default=False, help_text='Si cela est vrai, le rendez-vous est gratuit.')),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_rendez_vous', models.DateTimeField(blank=True, null=True)),
                ('lettre_orientation', models.FileField(blank=True, default='lettre.png', null=True, upload_to='lettres/%Y/%m/%d/')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_drdv', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_drdv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
