# Generated by Django 3.2.9 on 2022-08-29 15:16

import appointements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0002_demanderendezvous_destinataire_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lettre', models.FileField(blank=True, default='lettre.png', null=True, upload_to=appointements.models.lettre_path)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettres', to='appointements.demanderendezvous')),
            ],
        ),
    ]
