# Generated by Django 3.2.9 on 2022-08-31 13:10

import appointements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0003_amin_add_rdv_lettre_orient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettreorientation',
            name='lettre',
            field=models.FileField(blank=True, default='lettre.jpg', null=True, upload_to=appointements.models.lettre_path),
        ),
    ]
