# Generated by Django 3.2.9 on 2023-04-07 07:39

import appointements.models
import core.mime_types
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0004_amine_add_rdv_lettre_orient_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettreorientation',
            name='lettre',
            field=models.FileField(blank=True, default='lettre.jpg', null=True, upload_to=appointements.models.lettre_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
