# Generated by Django 3.2.9 on 2022-08-22 13:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointements', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Group channel name for this room', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tdemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('salle_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la salle de discussion')),
                ('mot_de_passe', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mot de passe')),
                ('annulee', models.BooleanField(default=False, verbose_name='Annulée')),
                ('acceptee', models.BooleanField(default=False, verbose_name='Acceptée')),
                ('facturee', models.BooleanField(default=False, verbose_name='Facturée')),
                ('tarif_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('tarif', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=Decimal('0'), default_currency='DZD', max_digits=14, null=True, verbose_name='Tarif')),
                ('gain_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('gain', djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=Decimal('0'), default_currency='DZD', max_digits=14, null=True, verbose_name='Gain')),
                ('from_patient', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
        migrations.CreateModel(
            name='TspeakerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dominant_speaker_time', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique conférencier',
                'verbose_name_plural': 'statistiques conférenciers',
            },
        ),
        migrations.CreateModel(
            name='Tsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(verbose_name='Date de création')),
                ('statistiques_conférenciers', models.ManyToManyField(blank=True, to='teleconsultation.TspeakerStats', verbose_name='Statistiques des conférenciers')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Treclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('message', models.TextField()),
                ('reponse', models.TextField(blank=True, null=True)),
                ('tdemande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teleconsultation.tdemand', verbose_name='Demande de Téléconsultation')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
            },
        ),
        migrations.CreateModel(
            name='Tfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('message', models.CharField(blank=True, choices=[('1', 'Acceptable'), ('2', 'Bon'), ('3', 'Mauvais')], max_length=1, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='tdemand',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, to='teleconsultation.Tfeedback', verbose_name='Feedbacks'),
        ),
        migrations.AddField(
            model_name='tdemand',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.medecin', verbose_name='Médecin'),
        ),
        migrations.AddField(
            model_name='tdemand',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='tdemand',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointements.demanderendezvous'),
        ),
        migrations.AddField(
            model_name='tdemand',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='teleconsultation.Tsession', verbose_name='Sessions'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Reply channel for connection that is present', max_length=255)),
                ('nombre_session', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('remove_busy_after', models.DateTimeField(blank=True, null=True)),
                ('busy', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsultation.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'channel_name')},
            },
        ),
    ]
