# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(editable=False, max_length=255, verbose_name='slug')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='Html Content')),
                ('draft', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('destination', models.CharField(choices=[('0', 'Patients'), ('1', 'Médecins'), ('2', 'Client'), ('3', 'User'), ('4', 'Contact')], max_length=2, verbose_name='Destination')),
                ('type', models.CharField(choices=[('0', 'Mail'), ('1', 'Sms')], default='0', max_length=2, verbose_name='Type')),
                ('criteria_exp', models.CharField(choices=[('0', 'Avant (exact)'), ('1', 'Après (exact)'), ('2', 'Après (Ou plus)'), ('3', 'Autre')], default='1', max_length=2, verbose_name='Condition')),
                ('criteria_days', models.IntegerField(blank=True, null=True, verbose_name='x Jour(s)')),
                ('criteria', models.CharField(blank=True, choices=[('1', 'Inscription'), ('2', 'Validation'), ('3', 'Connexion'), ('4', "Inscrit mais n'a pas choisi de profil patient"), ('5', 'Inscrit médecin mais pas activé'), ('6', "Expiration de l'abonnement"), ('7', 'Autre')], max_length=255, null=True, verbose_name='Critères')),
                ('criteria_json', models.JSONField(blank=True, null=True, verbose_name='Critères')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enewsletter.message', verbose_name='message')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enewsletter.newsletter', verbose_name='newsletter'),
        ),
    ]
