# Generated by Django 3.2.9 on 2022-08-22 13:04

import clinique.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CliniqueVirtuelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('fixe', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone Fixe')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone Mobile')),
                ('pageweb', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Page Web/Site Web')),
                ('facebook', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('gps', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('prestations', models.TextField(blank=True, null=True, verbose_name='Prestations')),
                ('salle_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la salle de discussion')),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CliniqueVirtuelleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='clinvirtimages/%Y/%m/%d/')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailClinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrdonnanceMedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('conditionnement', models.CharField(blank=True, max_length=255, null=True)),
                ('forme', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_commercial', models.CharField(blank=True, max_length=255, null=True)),
                ('dci', models.CharField(blank=True, max_length=255, null=True)),
                ('duree', models.CharField(blank=True, max_length=255, null=True)),
                ('posologie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('detailclinique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinique.detailclinique')),
                ('motif', models.TextField(blank=True, null=True)),
                ('interrogatoire', models.TextField(blank=True, null=True)),
                ('examen_clinique', models.TextField(blank=True, null=True)),
                ('examen_demande', models.TextField(blank=True, null=True)),
                ('resultat_examen', models.TextField(blank=True, null=True)),
                ('diag_suppose', models.TextField(blank=True, null=True)),
                ('diag_retenu', models.TextField(blank=True, null=True)),
                ('conduite_tenir', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('clinique.detailclinique',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('detailclinique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinique.detailclinique')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=clinique.models.document_path)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('clinique.detailclinique',),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('detailclinique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinique.detailclinique')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('clinique.detailclinique',),
        ),
    ]
