# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('clinique', '0001_initial'),
        ('drugs', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnancemedic',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.medicament'),
        ),
        migrations.AddField(
            model_name='detailclinique',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.patient'),
        ),
        migrations.AddField(
            model_name='detailclinique',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_clinique.detailclinique_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cliniquevirtuelleimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniquevirtuelle',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinique.cliniquevirtuelleimage'),
        ),
        migrations.AddField(
            model_name='cliniquevirtuelle',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cliniquevirtuelle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniquevirtuelle',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='ordonnancemedic',
            name='ordonance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinique.ordonnance'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments',
            field=models.ManyToManyField(through='clinique.OrdonnanceMedic', to='drugs.Medicament'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medecin'),
        ),
        migrations.AddField(
            model_name='document',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
