# Generated by Django 3.2.9 on 2023-04-07 07:39

import clinique.models
import core.mime_types
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniquevirtuelleimage',
            name='image',
            field=models.ImageField(upload_to='clinvirtimages/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=clinique.models.document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg']), core.mime_types.FileMimeTypeValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
