# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomComercialStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insertion', models.DateTimeField()),
                ('nomCommercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.nomcommercial')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poste')),
            ],
        ),
        migrations.CreateModel(
            name='AtcdciStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insertion', models.DateTimeField()),
                ('atcdci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.dciatc')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poste')),
            ],
        ),
    ]
