# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maj', models.DateTimeField(auto_now_add=True, null=True)),
                ('derniere_maj', models.BooleanField(default=True)),
                ('valeur_dun_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdreDePaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.IntegerField()),
                ('numero_autorisation', models.IntegerField(blank=True, null=True)),
                ('moyen_paiement', models.CharField(choices=[('1', 'Carte EDAHABIA')], default='1', max_length=2)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('Validé', 'Validé'), ('Expiré', 'Expiré'), ('Echec', 'Echec'), ('Annulé', 'Annulé')], default='En cours', max_length=50)),
                ('ordre_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
