# Generated by Django 3.2.9 on 2022-08-22 13:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import location_field.models.plain
import taggit_autosuggest.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('1', 'distanciel'), ('2', 'présentiel'), ('3', 'présentiel et distanciel')], default='1', max_length=2, verbose_name='Type')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Établissement')),
                ('emplacement', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('date_limite_inscription', models.DateTimeField(verbose_name="Date limite d'inscription")),
                ('payant', models.BooleanField(default=False)),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='DZD', editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='DZD', max_digits=14, verbose_name='Prix')),
                ('annule', models.BooleanField(default=False, verbose_name='Annulé')),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CongreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='congre/%Y/%m/%d/')),
                ('type', models.CharField(blank=True, choices=[('1', 'Banner'), ('2', 'Bannièrer sponsor gold'), ('3', 'logo sponsor gold'), ('4', 'autre sponsor')], max_length=2, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moderateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsor/%Y/%m/%d/')),
                ('type', models.CharField(blank=True, choices=[('1', '90x90'), ('2', '60x60')], max_length=2, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Libellé')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('1', 'webinaire'), ('2', 'Table Ronde'), ('3', 'Panel'), ('4', 'Cas Clinique interactif'), ('5', 'Session'), ('6', 'Quiz'), ('7', 'Plénière'), ('8', 'Conférence'), ('9', 'Conférence de prestige'), ('10', 'Flash Info'), ('11', 'Atelier'), ('12', 'Symposium')], default='1', max_length=3)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('salle_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la salle de discussion')),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe')),
                ('nb_max_participant', models.IntegerField(default=0, help_text='0 signifie pas de limite', verbose_name='Le nombre maximum de participants')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('date_diffustion', models.DateField(blank=True, null=True, verbose_name='Date de diffusion')),
                ('heure_debut_diffusion', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin_diffusion', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('salle_physique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salle physique')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('annule', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('congre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='econgre.congre')),
                ('moderateurs', models.ManyToManyField(blank=True, to='econgre.Moderateur')),
                ('speakers', models.ManyToManyField(blank=True, to='econgre.Speaker')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='econgre.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='econgre.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('url', models.URLField(verbose_name='URL')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls', to='econgre.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarStatistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField()),
                ('date_vision', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wvideo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='econgre.webinarvideo')),
            ],
        ),
        migrations.CreateModel(
            name='UserParticipationWebinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='econgre.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='congre',
            name='autre_sponsors',
            field=models.ManyToManyField(blank=True, to='econgre.CongreImage'),
        ),
        migrations.AddField(
            model_name='congre',
            name='banner_prog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bcongre_set', to='econgre.congreimage'),
        ),
        migrations.AddField(
            model_name='congre',
            name='organisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='econgre.organisateur'),
        ),
        migrations.AddField(
            model_name='congre',
            name='sponsor_gold_banniere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scongre_set', to='econgre.congreimage'),
        ),
        migrations.AddField(
            model_name='congre',
            name='sponsor_gold_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcongre_set', to='econgre.congreimage'),
        ),
        migrations.AddField(
            model_name='congre',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='CongressInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse e-mail')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé')),
                ('message', tinymce.models.HTMLField(verbose_name='Message')),
                ('type', models.CharField(choices=[('1', 'médecin')], default='1', max_length=2)),
                ('congre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='econgre.congre')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email', 'congre')},
            },
        ),
    ]
