# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('smsgateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsicosnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=160, null=True, verbose_name='Message')),
                ('reponse', models.TextField(blank=True, null=True, verbose_name='Reponse')),
                ('url', models.URLField()),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contact', verbose_name='Contact')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operateur')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smsgateway.smstemplate', verbose_name='SmsTemplate')),
            ],
        ),
    ]
