# Generated by Django 3.2.9 on 2022-08-31 08:07

from django.db import migrations, models

from smsicosnet.models import STATUS


def move_contact_to_source(apps, schema_editor):
    Smsicosnet = apps.get_model('smsicosnet', 'Smsicosnet')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for smsicosnet in Smsicosnet.objects.all():
        if smsicosnet.contact:
            source_type = ContentType.objects.get_for_model(smsicosnet.contact)
            smsicosnet.source_id = smsicosnet.contact.id
            smsicosnet.source_type = source_type
        if smsicosnet.template:
            smsicosnet.message = smsicosnet.template.content

        smsicosnet.save()

def update_status(apps, schema_editor):
    Smsicosnet = apps.get_model('smsicosnet', 'Smsicosnet')

    for smsicosnet in Smsicosnet.objects.all():
        if smsicosnet.reponse:
            if "1701" in smsicosnet.reponse:
                smsicosnet.status = STATUS.sent
            elif any(code in smsicosnet.reponse for code in
                     ["1702", "1703", "1704", "1705", "1706", "1707", "1708", "1709", "1710", "1725"]):
                smsicosnet.status = STATUS.failed
            elif "1715" in smsicosnet.reponse:
                smsicosnet.status = STATUS.requeued
            smsicosnet.save()

def move_source_to_contact(apps, schema_editor):
    Smsicosnet = apps.get_model('smsicosnet', 'Smsicosnet')
    Contact = apps.get_model('core', 'Contact')

    for smsicosnet in Smsicosnet.objects.all():
        if smsicosnet.source_id:
            if smsicosnet.source_type.app_label == "core" and smsicosnet.source_type.model == "contact":
                smsicosnet.contact = Contact.objects.get(id=smsicosnet.source_id)
                smsicosnet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('smsicosnet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=move_contact_to_source, reverse_code=move_source_to_contact),
        migrations.RemoveField(
            model_name='smsicosnet',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='smsicosnet',
            name='template',
        ),
        migrations.AddField(
            model_name='smsicosnet',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued'), (3, 'requeued')], db_index=True, null=True, verbose_name='Status'),
        ),
        migrations.RunPython(code=update_status, reverse_code=migrations.RunPython.noop),
    ]
