# Generated by Django 3.2.9 on 2022-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsicosnet', '0002_zahi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsicosnet',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
