"""
Django settings for etabibWebsite project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import string
from datetime import timedelta
from enum import Enum

import environ
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _


class Environment(Enum):
    DEV = "DEV"
    PROD = "PROD"
    BETA = "BETA"


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
env = environ.Env(
    ENABLE_WEB_ADS=(bool, True),
    ENABLE_WORKSPACE_ADS=(bool, True),
    DB_USER=(str, ''),
    DB_PASSWORD=(str, ''),
    DB_NAME=(str, ''),
    DB_HOST=(str, ''),
    DB_PORT=(str, ''),
    API_U=(str, ''),
    API_P=(str, ''),
    MISTSERVER_USERNAME=(str, ''),
    MISTSERVER_PASSWORD=(str, ''),
    MISTSERVER_ADMIN_URL=(str, ''),
    ROCKETCHAT_ADMIN_USERNAME=(str, ''),
    ROCKETCHAT_ADMIN_PASSWORD=(str, ''),
    ROCKETCHAT_DEFAULT_USER_PASSWORD=(str, ''),
    # Added for security
    SECRET_KEY=(str, ''),
    EMAIL_HOST=(str, ''),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    RECAPTCHA_PRIVATE_KEY=(str, ''),
    RECAPTCHA_PUBLIC_KEY=(str, ''),
    JWT_APP_SECRET=(str, ''),
    SH_ENCRYPTION_PASSWORD=(str, ''),
    SH_JWT_APP_SECRET=(str, ''),
    SMS_PASSWORD=(str, ''),
    PTRACK_SECRET=(str, ''),
    CORS_ORIGIN_ALLOW_ALL=(bool, True),
)
# reading .env file
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

ENVIRONMENT = Environment.DEV if env('PROJECT_ENV') == Environment.DEV.value else Environment.PROD if env(
    'PROJECT_ENV') == Environment.PROD.value else Environment.BETA

if ENVIRONMENT == Environment.DEV:
    DEBUG = True
else:
    DEBUG = False
if ENVIRONMENT == Environment.DEV:
    ALLOWED_HOSTS = ["*"]
elif ENVIRONMENT in (Environment.PROD, Environment.BETA):
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "etabibstore.com", "www.etabibstore.com",
                     "etabib-store.com", "www.etabib-store.com", "test.etabib.tk", "etabibstoretest.tk",
                     "store.etabib.dz"]
    # [PATCH] Add hosts from environment variable (e.g. for API, Safeline, etc.)
    env_hosts = env.list('ALLOWED_HOSTS', default=[])
    if env_hosts:
        ALLOWED_HOSTS.extend(env_hosts)

ADMINS = [('Zahi Messaoud', 'zahi.ihsm@gmail.com'), ('Makti Moncef', 'maktimoncef@gmail.com'),]

# Application definition

INSTALLED_APPS = [
    'docs',
    'admin_interface',
    "colorfield",

    ###
    'dal',  # autocomplete-light
    'dal_select2',  # autocomplete-light
    'django.contrib.admin',
    'django.contrib.auth',
    'polymorphic',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'tinymce',
    'widget_tweaks',
    'django_inlinecss',
    'cities_light',
    'el_pagination',
    # Django Taggit widget
    'taggit_autosuggest',
    # taggit
    'taggit',
    'tracking',
    'post_office',  # A Django app that allows you to send email asynchronously in Django
    'core',
    'dropzone',
    'api',
    'datatableview',  # databtable
    # ajax modals
    'crispy_forms',
    # ajax modals
    'fm',
    # datepicker
    'bootstrap_datepicker_plus',
    # import_export
    'import_export',
    #
    'django_celery_beat',  # Celery Periodic Tasks backed by the Django ORM
    'django_celery_results',  # Celery Result Backends using the Django ORM/Cache framework
    #
    'notifications',  # is a GitHub notification alike app for Django
    #
    'channels',  # Channels augments Django to bring WebSocket, long-poll HTTP, task offloading and other async support
    #
    'imagekit',  # Automated image processing for Django
    #
    "sslserver",  # Django SSL Server is a SSL-enabled development server for the Django Framework.
    #
    'snowpenguin.django.recaptcha3',  # GOOGLE recaptcha3
    #
    'basket',
    #
    'drf_yasg',
    # drf-tracking provides a Django model and DRF view mixin that work together to log Django Rest Framework requests to the database
    'rest_framework_tracking',
    # Money fields for django forms and models.
    'djmoney',
    'ajax_datatable',
    # A new model field and form field. With this you can get a multiple select from a choices
    'multiselectfield',
    # Django Duration Widget
    'durationwidget',
    # Drugs App
    'drugs',
    # Nomenclature app
    'nomenclature',
    # Statistics app
    'stats',
    # The django-analytical application integrates analytics services into a Django project.
    'analytical',
    #
    'teleconsultation',
    # django-formtools is a collection of assorted utilities that are useful for specific form use cases.
    'formtools',
    # A django model and form field for normalised phone numbers using python-phonenumbers
    'phonenumber_field',
    'econgre',
    # 'django_extensions',
    # Django-invitations - Generic invitations app
    'invitations',
    'appointements',
    'epayment',
    'captcha',
    'gdstorage',  # GOOGLE Drive Storage
    'location_field.apps.DefaultConfig',
    'django_extensions',
    # The django-location-field app provides model and form fields, and widgets that allows your users to easily pick locations and store in the database
    'filesharing',  # share file between a patient and list of doctors
    'rosetta',  # Rosetta is a Django application that facilitates the translation process of your Django projects.
    'smsgateway',
    'smsicosnet',
    'coupons',
    "bidiutils",  # Provides context processors and filters for handling Bi-directional (BiDi) in django templates
    'django_toggle_switch_widget',  # Display toggle switch in stead of checkbox for BooleanField in django admin site.
    'enewsletter',
    'guardian',
    # django-guardian is an implementation of object permissions for Django providing an extra authentication backend.
    "qr_code",
    "embed_video",  # Django app for easy embedding YouTube and Vimeo videos
    'drf_multiple_model',
    'corsheaders',
    'clinique',
    'directory',
    'crm',
    'expo',
    'ads',
    'store',
    'django.contrib.gis',
    'ptrack',  # Ptrack is a tracking pixel library for Django.
    'maintenance_mode',
    'dicom',
    'sorl.thumbnail',
    'rangefilter',
    'dbbackup',  # django-dbbackup
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'tracking.middleware.VisitorTrackingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.notification_middleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'core.middleware.profile_middleware',
    'directory.middleware.rdv_middleware',
]

LANGUAGES = (
    ('ar', _('Arabic')),
    ('fr', _('French')),
    ('en', _('English')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
    os.path.join(BASE_DIR, 'core', 'locale'),
)

ROOT_URLCONF = 'etabibWebsite.urls'

TEMPLATES = [
    {
        'NAME': "v1",
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'OPTIONS': {
            'loaders': [
                (
                    'django.template.loaders.filesystem.Loader',
                    [os.path.join(BASE_DIR, 'templates/v1')],
                ),
                'django.template.loaders.app_directories.Loader',
                'core.loaders.AppDirV1Loader'
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',  ## For EL-pagination
                "bidiutils.context_processors.bidi",
                "core.context_processors.advanced_search",
            ],
        },
    }, {
        'NAME': "v2",
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'OPTIONS': {
            'loaders': [
                (
                    'django.template.loaders.filesystem.Loader',
                    [os.path.join(BASE_DIR, 'templates/v2')],
                ),
                'django.template.loaders.app_directories.Loader',
                'core.loaders.AppDirV2Loader'
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',  ## For EL-pagination
                "bidiutils.context_processors.bidi",
                "core.context_processors.advanced_search",
            ],
        },
    },
]

WSGI_APPLICATION = 'etabibWebsite.wsgi.application'

if ENVIRONMENT != Environment.DEV:
    SESSION_COOKIE_SECURE = True
    SESSION_SAVE_EVERY_REQUEST = True
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',
        'NAME': env("DB_NAME"),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {
            "init_command": "SET default_storage_engine=InnoDB",
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATICFILES_DIRS = (
)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# ===============================================================================
# TINYMCE Editor configurations
# ===============================================================================
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,anchor,"
               "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
               "code,help,wordcount",
    "toolbar": "undo redo | formatselect | "
               "bold italic backcolor | alignleft aligncenter "
               "alignright alignjustify | bullist numlist outdent indent | "
               "removeformat | help",
    "setup": "function(editor){editor.on('change', function(){editor.save();});}",
}

# ===============================================================================
# Events Configuration
# ===============================================================================
CALENDAR_WEEKEND = [5, 4]  # friday, satuday
CALENDAR_DAYS_TO_SHIFT = 10
# ===============================================================================
# Email Configuration
# ===============================================================================
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
if EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = 'eTabib <%s>' % EMAIL_HOST_USER
else:
    DEFAULT_FROM_EMAIL = 'eTabib <no-reply@etabib.dz>'
EMAIL_BACKEND = 'post_office.EmailBackend'
# ===============================================================================
# Djngo allAuth Configuration
# ===============================================================================
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_ADAPTER = "core.adapter.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "core.adapter.SocialAccountAdapter"
ACCOUNT_EMAIL_VERIFICATION = "optional"
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
ACCOUNT_SIGNUP_FORM_CLASS = 'core.forms.forms.LocalSignupForm'
LOGIN_URL = "/login"
if ENVIRONMENT != Environment.DEV:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
# ===============================================================================
# Django cities light Configurations
# ===============================================================================
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['fr', 'ar']
CITIES_LIGHT_INDEX_SEARCH_NAMES = False
CITIES_LIGHT_INCLUDE_COUNTRIES = ['DZ', 'MA', 'TN', 'LY', 'EG', 'SA', 'MR']
CITIES_LIGHT_TRANSLATION_SOURCES = ['http://download.geonames.org/export/dump/alternateNamesV2.zip']
CITIES_LIGHT_CITY_SOURCES = [
    'http://download.geonames.org/export/dump/DZ.zip',
    'http://download.geonames.org/export/dump/MA.zip',
    'http://download.geonames.org/export/dump/TN.zip',
    'http://download.geonames.org/export/dump/LY.zip',
    'http://download.geonames.org/export/dump/EG.zip',
    'http://download.geonames.org/export/dump/SA.zip',
    'http://download.geonames.org/export/dump/MR.zip'
]
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF',
                                   'PPLG', 'PPLL', 'PPLR', 'PPLS', 'ADM1', 'ADM2', 'ADM3', 'ADM4']
# ===============================================================================
# Celery settings
# ===============================================================================
# CELERY STUFF
CELERY_BROKER_URL = 'redis://{}:6379/0'.format(env('REDIS_HOST', default='etabib_redis'))
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191
# ===============================================================================
#  Django el Pagination Configurations
# ===============================================================================
EL_PAGINATION_PER_PAGE = 10
# ===============================================================================
# Django
# ===============================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://{}:6379/4".format(env('REDIS_HOST', default='etabib_redis')),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
    }
}
# ===============================================================================
# Django Fm
# ===============================================================================
CRISPY_TEMPLATE_PACK = 'bootstrap3'
FM_DEFAULT_FORM_TEMPLATE = "fm/form.html"

# ===============================================================================
# Django Taggit
# ===============================================================================
TAGGIT_AUTOSUGGEST_CSS_FILENAME = 'autoSuggest-grappelli.css'

# ===============================================================================
# Django Post Office
# ===============================================================================
POST_OFFICE = {
    'DEFAULT_PRIORITY': 'medium',
    'MAX_RETRIES': 4,
    'RETRY_INTERVAL': timedelta(minutes=1),  # Schedule to be retried 1 minutes later
    'OVERRIDE_RECIPIENTS': None if ENVIRONMENT in (Environment.PROD, Environment.BETA) else ['zahi.ihsm@gmail.com'],
}

# ===============================================================================
# Django Channels configurations
# ===============================================================================
ASGI_APPLICATION = "etabibWebsite.asgi.application"
if ENVIRONMENT == Environment.BETA:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [
                    {
                        "address": (env('REDIS_HOST', default='localhost'), 6379),
                        "db": 2,
                    }
                ],
                'capacity': 300,
                'prefix': "asgi:%s:" % ENVIRONMENT
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [
                    {
                        "address": (env('REDIS_HOST', default='localhost'), 6379),
                        "db": 1,
                    }
                ],
                'capacity': 1500,
                'prefix': "asgi:%s:" % ENVIRONMENT
            },
        },
    }

# ===============================================================================
# Django Notifications configurations
# ===============================================================================
DJANGO_NOTIFICATIONS_CONFIG = {'SOFT_DELETE': True, 'USE_JSONFIELD': True}

# ===============================================================================
# Django reCaptcha v3 configurations
# ===============================================================================
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY')
RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.5

# ===============================================================================
# Django basket configurations
# ===============================================================================
CART_PRODUCT_MODEL = 'core.models.Module'
# ===============================================================================
# Django rest framwork configurations
# ===============================================================================
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#     ),
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DATETIME_FORMAT': "%Y-%m-%d a %H:%M:%S",
}
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'api.serializers.auth_serializers.PatientRegisterSerializer',
}
# ===============================================================================
# Django-money
# ===============================================================================
CURRENCIES = ('DZD', 'USD', 'EUR')
# ===============================================================================
# Ads configurations
# ===============================================================================
ENABLE_WEB_ADS = env('ENABLE_WEB_ADS')
ENABLE_WORKSPACE_ADS = env('ENABLE_WORKSPACE_ADS')
ADS_200x360_WIDTH = 200
ADS_200x360_HEIGHT = 360
ADS_728x360_WIDTH = 728
ADS_728x360_HEIGHT = 360
ADS_500x360_WIDTH = 500
ADS_500x360_HEIGHT = 360
ADS_450x416_WIDTH = 450
ADS_450x416_HEIGHT = 416
ADS_1600x840_WIDTH = 1422
ADS_1600x840_HEIGHT = 800
ADS_IMAGE_SIZE_CHOICES = (
    ("1", "728x90"),  # deprecated
    ("2", "450x416"),
    ("3", "200x360"),
    ("4", "500x360"),
    ("5", "728x360"),
    ("6", "1600x840"),
)
ADS_MAX_VIDEO_SIZE = 25  # MB
ADS_MAX_VIDEO_DURATION = 10  # seconds
CONGRE_VIDEO_DURATION = 10  # seconds
# =========================================================================
# Swagger Settings
# =========================================================================
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Mac': {
            'type': 'apiKey',
            'name': 'mac',
            'in': 'header'
        }
    }
}
# =========================================================================
# Django Analytical Settings
# =========================================================================
GOOGLE_ANALYTICS_PROPERTY_ID = 'UA-156265522-1'
ANALYTICAL_INTERNAL_IPS = ['127.0.0.1', '0.0.0.0']
# =========================================================================
# Teleconsultation configuration
# =========================================================================
DOCTORS_CHANNEL = "DOCTORS"
PATIENTS_CHANNEL = "PATIENTS"
CANCELLATION_TIME = 40
TIME_BETWEEN_DEMANDS = 60
if ENVIRONMENT not in (Environment.BETA, Environment.DEV):
    ECONSULTATION_JITSI_DOMAIN_NAME = 'econsulation.etabib.dz'
    ECONGRE_JITSI_DOMAIN_NAME = 'econsulation.etabib.dz'
elif ENVIRONMENT == Environment.DEV:
    ECONSULTATION_JITSI_DOMAIN_NAME = 'localhost:8443'
    ECONGRE_JITSI_DOMAIN_NAME = 'localhost:8443'
else:
    ECONSULTATION_JITSI_DOMAIN_NAME = 'econsulation.etabib.dz'
    ECONGRE_JITSI_DOMAIN_NAME = 'econsulation.etabib.dz'
JWT_APP_ID = "etabib_app_id"
JWT_APP_SECRET = env('JWT_APP_SECRET')
ETABIB_ECONSULTATION_AMOUNT = 0
ETABIB_ECONSULTATION_CURRENCY = 'DZD'
# =========================================================================
# Django phonenumber field Settings
# =========================================================================
PHONENUMBER_DEFAULT_REGION = 'DZ'
PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL'
# =========================================================================
# Django Invitations & eCongre Configuration
# =========================================================================
INVITATIONS_INVITATION_MODEL = "econgre.CongressInvitation"
# INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = True
INVITATIONS_ADAPTER = ACCOUNT_ADAPTER
INVITATIONS_ACCEPT_INVITE_AFTER_FINAL_SIGNUP = True
ECONGRE_SPONSOR_IMAGE_SIZE = 2  # MB
ECONGRE_IMAGE_SIZE = 2  # MB
# =========================================================================
# Django SIMPLE CAPTCHA
# =========================================================================
CAPTCHA_LETTER_ROTATION = (-1, 1)
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
# =========================================================================
# TERMS OF SERVICES
# =========================================================================
TOS_PATIENT = "https://etabib.dz/cloud/index.php/s/PA5QAazRi8WxH58"
TOS_DOCTOR = "https://etabib.dz/cloud/index.php/s/93W48wr9woSs5jw"
TOS_ETABIB_VISIO = "https://etabib.dz/cloud/index.php/s/DXsTgBpXkYNJr7H"
TOS_ADS = "https://etabib.dz/cloud/index.php/s/9FagyFkaYGQgaTw"

# Links for future implementation
PRIVACY_POLICY = "https://etabib.dz/cloud/index.php/s/nB77fToyNpcrmyA"
TOS_ETABIBSTORE = "https://etabib.dz/cloud/index.php/s/LjYRd9ow24eS5xA"
DEONTOLOGY_CHARTER = "https://etabib.dz/cloud/index.php/s/2nY4yN7iJCo7G6B"
# =========================================================================
# Google Drive Storage Configuratoions
# =========================================================================
if ENVIRONMENT == Environment.DEV:
    GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = os.path.join(BASE_DIR, ".google-drive-dev.json")
else:
    GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = os.path.join(BASE_DIR, ".google-drive-prod.json")
# =========================================================================
# django-location-field Configuratoions
# =========================================================================
LOCATION_FIELD = {
    'map.provider': 'openstreetmap',
    'provider.openstreetmap.max_zoom': 18,
    'map.zoom': 14,
    'search.provider': 'nominatim',
}
# =========================================================================
# django filesharing configurations
# =========================================================================
SH_LOCAL_SERVER_IDENTITY = "store.etabib.dz"  # used to create a unique identifier for the patient
if ENVIRONMENT == Environment.DEV:
    SH_SERVER_HOSTNAME = "127.0.0.1:8001"
    SH_SERVER_PROTOCOL = "http"
elif ENVIRONMENT == Environment.PROD:
    # PLEASE Do not use the production server in development environment
    # This will create a big conflicts
    SH_SERVER_HOSTNAME = "e-tabeeb.com"
    SH_SERVER_PROTOCOL = "https"
elif ENVIRONMENT == Environment.BETA:
    SH_SERVER_HOSTNAME = ""
    SH_SERVER_PROTOCOL = ""

SH_ENCRYPTION_PASSWORD = env('SH_ENCRYPTION_PASSWORD')
SH_FETCH_PATIENT_FILES_ENDPOINT = "%s://%s/api/patient/file/list/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_FETCH_DOCTOR_FILES_ENDPOINT = "%s://%s/api/doctor/file/list/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_UPLOAD_FILE_ENDPOINT = "%s://%s/api/file/upload" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_DELETE_FILE_ENDPOINT = "%s://%s/api/file/delete/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_GET_FILE_ENDPOINT = "%s://%s/api/file/get/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_RETRIEVE_FILE_ENDPOINT = "%s://%s/api/file/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_SHARE_FILE_ENDPOINT = "%s://%s/api/file/share" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_RENAME_FILE_ENDPOINT = "%s://%s/api/file/rename" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_FILE_SHARED_WITH_ENDPOINT = "%s://%s/api/file/user/list/" % (
    SH_SERVER_PROTOCOL, SH_SERVER_HOSTNAME
)
SH_JWT_ISSUER = "file_sharing_api"
SH_JWT_AUDIENCE = "eTabib file sharing"
SH_JWT_APP_SECRET = env('SH_JWT_APP_SECRET')

# =========================================================================
# django django-rosetta configurations
# =========================================================================
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
    ('ar', _('Arabic')),
)
# =========================================================================
# Sms Icosnet
# =========================================================================
SMS_ICOSNET_ENABLED = True
# =========================================================================
# Sms Number
# =========================================================================
SMS_PASSWORD = {
    'Password': env('SMS_PASSWORD'),
}
SMS_PHONE = {
    'Sim1': '0791505797',
    'Sim2': '0542456230',
}
SMS_DAILY_QUOTA = 40
SMS_ENABLED = True
# =========================================================================
# Facturation
# =========================================================================
TVA = 19  # 0%
# =========================================================================
# ePayment
# =========================================================================
EPAYMENT_REGISTER_URL = "https://epay.poste.dz/payment/rest/register.do"
EPAYMENT_ORDER_STATU_URL = 'https://epay.poste.dz/payment/rest/getOrderStatusExtended.do'
# ===========================================================================
# COUPONS Configuration
# ===========================================================================
COUPONS_CODE_LENGTH = 6
COUPONS_COUPON_TYPES = (
    ('percentage', 'Percentage discount'),
    ('monetary', 'Money based coupon'),
    ('sponsorship', 'Sponsorship'),
)
COUPONS_CODE_CHARS = string.ascii_uppercase + string.digits
# ===========================================================================
# Mistserver Configuration
# ===========================================================================
MISTSERVER_USERNAME = env('MISTSERVER_USERNAME')
MISTSERVER_PASSWORD = env('MISTSERVER_PASSWORD')
MISTSERVER_ADMIN_URL = env('MISTSERVER_ADMIN_URL')
# ===========================================================================
# Rocket chat configuration
# ===========================================================================
ROCKET_CHAT_SERVER = "https://etabibchat.tk/"
ROCKETCHAT_ADMIN_USERNAME = env("ROCKETCHAT_ADMIN_USERNAME")
ROCKETCHAT_ADMIN_PASSWORD = env("ROCKETCHAT_ADMIN_PASSWORD")
ROCKETCHAT_DEFAULT_USER_PASSWORD = env("ROCKETCHAT_DEFAULT_USER_PASSWORD")
# ===========================================================================
# Django guardian configuration
# ===========================================================================
GUARDIAN_RENDER_403 = True
# ===========================================================================
# Django Traking
# ===========================================================================
TRACK_AJAX_REQUESTS = False
TRACK_ANONYMOUS_USERS = False
TRACK_SUPERUSERS = False
TRACK_PAGEVIEWS = True
TRACK_IGNORE_URLS = ["^media", "^static"]
# ===========================================================================
# Django CorsMiddleware
# ===========================================================================
CORS_ORIGIN_ALLOW_ALL = env.bool('CORS_ORIGIN_ALLOW_ALL', default=True)
# ===========================================================================
# Django PTRACK configurations
# ===========================================================================
PTRACK_SECRET = env('PTRACK_SECRET')
if ENVIRONMENT == Environment.DEV:
    PTRACK_APP_URL = "http://127.0.0.1:8000"
elif ENVIRONMENT == Environment.PROD:
    PTRACK_APP_URL = "https://store.etabib.dz"
if ENVIRONMENT == Environment.BETA:
    PTRACK_APP_URL = "https://etabibstoretest.tk"
# ===========================================================================
# Django admin-interface configurations
# ===========================================================================
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MAINTENANCE_MODE = False
# ===========================================================================
# DB backup
# ===========================================================================
DBBACKUP_CLEANUP_KEEP = 2
DBBACKUP_CLEANUP_KEEP_MEDIA = 2
if ENVIRONMENT == Environment.DEV:
    DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
    DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR, 'backups'), }
elif ENVIRONMENT == Environment.PROD:
    DBBACKUP_STORAGE = 'storages.backends.ftp.FTPStorage'
    DBBACKUP_STORAGE_OPTIONS = {'location': f"ftp://{env('FTP_USER')}:{env('FTP_PASSWORD')}@{env('FTP_HOSTNAME')}:21/etabibstore"}
