# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauVersement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField()),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereau_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nom_ar', models.CharField(max_length=255)),
                ('daira_code', models.CharField(blank=True, max_length=255, null=True)),
                ('daira_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('daira_nom_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('cl_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pays')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commandes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre', models.CharField(blank=True, choices=[('', '----'), ('0', 'Abonement Trimestriel'), ('1', 'Abonement Annuel'), ('2', 'Abonement 18 Mois')], default='', max_length=5, verbose_name='Offre')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('methode_paiement', models.CharField(blank=True, choices=[('', '----'), ('0', 'Espèce'), ('1', 'Chèque'), ('2', 'TPE')], default='', max_length=5, verbose_name='Méthode de paiement')),
                ('versement_initial', models.IntegerField(default=0, verbose_name='Versement initial')),
                ('traitee', models.BooleanField(default=False, verbose_name='Traitée')),
                ('totalHt', models.FloatField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('bordereau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.bordereauversement')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('detail_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.detailaction')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commandeimage', verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
