# Generated by Django 3.2.9 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DciAtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('designation_en', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_sp', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_ch', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_de', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_nl', models.CharField(blank=True, db_column='designation__nl', max_length=255, null=True)),
                ('designation_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('mpgrp', models.CharField(blank=True, db_column='MPGRP', max_length=255, null=True)),
                ('ti', models.CharField(blank=True, db_column='TI', max_length=255, null=True)),
                ('intro', models.TextField(blank=True, db_column='INTRO', null=True)),
                ('posol', models.TextField(blank=True, db_column='POSOL', null=True)),
                ('narcotic', models.CharField(blank=True, db_column='Narcotic', max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormeHomogene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dci_pays', models.CharField(max_length=255)),
                ('num_enregistrement', models.CharField(blank=True, max_length=25, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('forme', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('cond', models.CharField(blank=True, max_length=255, null=True)),
                ('liste', models.CharField(blank=True, max_length=64, null=True)),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=255, null=True)),
                ('note_medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('duree_stabilitee', models.CharField(blank=True, max_length=255, null=True)),
                ('remboursable', models.CharField(blank=True, max_length=5, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
                ('autorise', models.CharField(blank=True, max_length=5, null=True)),
                ('date_retrait', models.CharField(blank=True, max_length=255, null=True)),
                ('motif_retrait', models.TextField(blank=True, null=True)),
                ('pays_labo', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentCnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_enregistrement', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nom_commercial', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_dci', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('unite', models.CharField(blank=True, max_length=255, null=True)),
                ('conditionnement', models.CharField(blank=True, max_length=255, null=True)),
                ('convention', models.CharField(blank=True, max_length=255, null=True)),
                ('remboursable', models.CharField(blank=True, max_length=255, null=True)),
                ('date_remboursement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_arret_remboursement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('tarif_de_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('taux', models.CharField(blank=True, max_length=255, null=True)),
                ('forme', models.IntegerField(blank=True, null=True)),
                ('tableau', models.CharField(blank=True, max_length=255, null=True)),
                ('hopital', models.CharField(blank=True, max_length=255, null=True)),
                ('secteur_sanitaire', models.CharField(blank=True, max_length=255, null=True)),
                ('officine', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratoire', models.CharField(blank=True, max_length=255, null=True)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('code_medic', models.CharField(blank=True, max_length=255, null=True)),
                ('date_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('code_dci', models.CharField(blank=True, max_length=255, null=True)),
                ('inf_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('generic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentCnasForme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_court', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NomCommercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nom_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_en', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_sp', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_de', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_ch', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pays', models.CharField(blank=True, max_length=10, null=True)),
                ('designation_fr', models.CharField(max_length=255)),
                ('en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=True)),
                ('date_update', models.DateTimeField(blank=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.medicament')),
                ('professionnel_sante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.professionnelsante')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('posologie', models.CharField(max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.mediccategorie'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='dci_atc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.dciatc'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme_homogene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.formehomogene'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='labo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.laboratoire'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='nom_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.nomcommercial'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pays_marche',
            field=models.ForeignKey(db_column='pays_marche', on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.pays'),
        ),
        migrations.CreateModel(
            name='MapCnas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remborsable', models.CharField(blank=True, choices=[('O', 'O'), ('H', 'H'), ('N', 'N')], max_length=5, null=True)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id')),
                ('medicamentcnas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.medicamentcnas', to_field='n_enregistrement')),
            ],
        ),
        migrations.CreateModel(
            name='MapAutorise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorise', models.CharField(blank=True, choices=[('NR', 'NR'), ('A', 'A'), ('R', 'R')], max_length=5, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_interraction', models.CharField(blank=True, max_length=25, null=True)),
                ('risque', models.CharField(blank=True, max_length=422, null=True)),
                ('cat', models.CharField(blank=True, max_length=461, null=True)),
                ('dci_atc_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_dci_atc_a_set', to='drugs.dciatc')),
                ('dci_atc_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_dci_atc_b_set', to='drugs.dciatc')),
            ],
        ),
        migrations.CreateModel(
            name='CodeAtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('ddd', models.FloatField(blank=True, null=True)),
                ('ddu', models.CharField(blank=True, max_length=5, null=True)),
                ('ti', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('narcotic', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dciAtc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.dciatc')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Amm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amm', models.CharField(blank=True, max_length=255, null=True)),
                ('date_retrait', models.CharField(blank=True, max_length=255, null=True)),
                ('motif_retrait', models.CharField(blank=True, max_length=255, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id')),
            ],
        ),
    ]
