# Generated by Django 3.2.9 on 2023-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dciatc',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
