# Generated by Django 3.2.9 on 2023-02-09 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_makti'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDrugs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
