# Generated by Django 3.2.9 on 2023-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_makti'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediccategorie',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
