# Generated by Django 3.2.9 on 2023-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_makti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedrugs',
            name='query',
            field=models.CharField(max_length=2000),
        ),
    ]
