# Generated by Django 3.2.9 on 2023-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_makti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeatc',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
