# Generated by Django 3.2.9 on 2023-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_makti'),
    ]

    operations = [
        migrations.RunSQL("UPDATE `drugs_laboratoire` SET `unique_id` = '594' WHERE `drugs_laboratoire`.`id` = 47"),
        migrations.AlterField(
            model_name='laboratoire',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
