# Generated by Django 3.2.9 on 2023-02-27 10:23

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_makti'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='categorie_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_categorie_new', to='drugs.mediccategorie', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='dci_atc_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_dci_atc_new', to='drugs.dciatc', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme_homogene_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_forme_homogene_new', to='drugs.formehomogene', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='labo_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_labo_new', to='drugs.laboratoire', to_field='unique_id'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='nom_commercial_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_nom_commercial_new', to='drugs.nomcommercial', to_field='unique_id'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_categorie', to='drugs.mediccategorie'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dci_atc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_dci_atc', to='drugs.dciatc'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='forme_homogene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_forme_homogene', to='drugs.formehomogene'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='labo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_labo', to='drugs.laboratoire'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicaments_nom_commercial', to='drugs.nomcommercial'),
        ),

    ]
