# Generated by Django 3.2.9 on 2023-02-28 08:30

from django.db import migrations, models
import django.db.models.deletion


def update_medicament_nom_commercial(apps, schema_editor):
    Medicament = apps.get_model('drugs', 'Medicament')

    # Loop over all Medicament records
    for medicament in Medicament.objects.all():
        dci_atc_unique_id = medicament.dci_atc if medicament.dci_atc else None
        nom_commercial_unique_id = medicament.nom_commercial if medicament.nom_commercial else None
        forme_homogene_unique_id = medicament.forme_homogene if medicament.forme_homogene else None
        categorie_unique_id = medicament.categorie if medicament.categorie else None
        labo_unique_id = medicament.labo if medicament.labo else None

        # Update the Medicament object with the unique IDs
        Medicament.objects.filter(pk=medicament.pk).update(
            dci_atc_new=dci_atc_unique_id,
            nom_commercial_new=nom_commercial_unique_id,
            forme_homogene_new=forme_homogene_unique_id,
            categorie_new=categorie_unique_id,
            labo_new=labo_unique_id
        )


class Migration(migrations.Migration):
    dependencies = [
        ('drugs', '0012_makti'),
    ]

    operations = [

        migrations.RunPython(update_medicament_nom_commercial),
    ]
