
# Generated by Django 3.2.9 on 2023-02-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_makti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='dci_atc',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='forme_homogene',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='labo',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='nom_commercial',
        ),
    ]
