# Generated by Django 3.2.9 on 2023-02-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_makti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='categorie_new',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='dci_atc_new',
            new_name='dci_atc',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='forme_homogene_new',
            new_name='forme_homogene',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='labo_new',
            new_name='labo',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='nom_commercial_new',
            new_name='nom_commercial',
        ),
    ]
