# Generated by Django 3.2.9 on 2023-02-28 09:45

from django.db import migrations, models
import django.db.models.deletion

def update_medicament_codeatc(apps, schema_editor):
    CodeAtc = apps.get_model('drugs', 'CodeAtc')

    # Loop over all Medicament records
    for codeatc in CodeAtc.objects.all():
        dci_atc_unique_id = codeatc.dciAtc if codeatc.dciAtc else None

        # Update the Medicament object with the unique IDs
        CodeAtc.objects.filter(pk=codeatc.pk).update(
            dci_atc=dci_atc_unique_id,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_makti'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeatc',
            name='dci_atc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='codeatc_dci_atc_new', to='drugs.dciatc', to_field='unique_id'),
        ),
        migrations.RunPython(update_medicament_codeatc),

    ]

