# Generated by Django 3.2.9 on 2023-02-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0016_makti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeatc',
            name='dciAtc',
        ),
    ]
