# Generated by Django 3.2.9 on 2023-02-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0017_makti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeatc',
            old_name='dci_atc',
            new_name='dciAtc',
        ),
    ]
