# Generated by Django 3.2.9 on 2023-04-17 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0018_makti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapautorise',
            name='medicament',
            field=models.ForeignKey(default=datetime.datetime(2023, 4, 17, 16, 45, 2, 251276, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id'),
            preserve_default=False,
        ),
    ]
