# Generated by Django 3.2.9 on 2023-04-17 17:08

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count

def delete_duplicate_map_autorise(apps, schema_editor):
    MapAutorise = apps.get_model('drugs', 'MapAutorise')
    # Get all map autorise instances
    map_autorises = MapAutorise.objects.all()
    # Group them by medicament_id and get the instances with count greater than 1
    grouped_map_autorises = map_autorises.values('medicament_id').annotate(count=Count('id')).filter(count__gt=1)
    # Get the ids of instances to delete
    delete_ids = []
    for d in grouped_map_autorises:
        medicament_id = d['medicament_id']
        # Get the instances and exclude the one with minimum id
        instances_to_delete = map_autorises.filter(medicament_id=medicament_id).exclude(
            id=map_autorises.filter(medicament_id=medicament_id).order_by('id').first().id)
        # Add the ids of the instances to delete to the delete list
        delete_ids += list(instances_to_delete.values_list('id', flat=True))
    # Delete the duplicate instances
    MapAutorise.objects.filter(id__in=delete_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0019_makti'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_map_autorise),
        migrations.AlterField(
            model_name='mapautorise',
            name='medicament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament',
                                       to_field='unique_id'),
        ),
    ]
