# Generated by Django 3.2.9 on 2023-04-19 14:01

from django.db import migrations, models
from django.db.models import Count
import django.utils.timezone

def delete_duplicate_map_cnas(apps, schema_editor):
    MapCnas = apps.get_model('drugs', 'MapCnas')
    # Get all MapCnas instances and group them by medicament_id
    map_cnas_list = MapCnas.objects.all().values('medicament_id')
    # Filter medicament_id that appear more than once
    medicament_ids_with_duplicates = map_cnas_list.annotate(count=Count('medicament_id')).filter(count__gt=1)
    # Create a list to store the ids of MapCnas instances to keep
    ids_to_keep = []
    for medicament_id in medicament_ids_with_duplicates:
        # Get the first MapCnas instance for this medicament_id and add its id to the list to keep
        map_cnas_to_keep = MapCnas.objects.filter(medicament_id=medicament_id['medicament_id']).first()
        ids_to_keep.append(map_cnas_to_keep.id)
    # Delete all the MapCnas instances that are not in the ids_to_keep list
    MapCnas.objects.exclude(id__in=ids_to_keep).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0020_makti'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_map_cnas),
        migrations.AlterField(
            model_name='mapcnas',
            name='medicament',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id'),
        ),
    ]