# Generated by Django 3.2.9 on 2024-12-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0021_makti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcnas',
            name='medicament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drugs.medicament', to_field='unique_id'),
        ),
    ]
